<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">getConfig</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:0:required assetType</value>
    <value>[o] record:0:required config</value>
  </array>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">CQlJRGF0YUN1cnNvciBwaXBlbGluZUN1cnNvciA9IHBpcGVsaW5lLmdldEN1cnNvcigpOw0KCQlT
dHJpbmcgYXNzZXRUeXBlID0gSURhdGFVdGlsLmdldFN0cmluZyhwaXBlbGluZUN1cnNvciwgImFz
c2V0VHlwZSIpOw0KCQlpZiAoYXNzZXRUeXBlID09IG51bGwgfHwgIiIuZXF1YWxzKGFzc2V0VHlw
ZSkpIHsNCgkJCXRocm93IG5ldyBTZXJ2aWNlRXhjZXB0aW9uKCJhc3NldFR5cGUgbXVzdCBub3Qg
YmUgZW1wdHkiKTsNCgkJfQ0KCQlKc29uVmFsdWUgakNvbmZpZyA9IF9jb25maWd1cmF0aW9ucy5n
ZXQoYXNzZXRUeXBlKTsNCgkJaWYgKGpDb25maWcgPT0gbnVsbCkgew0KCQkJbG9nZ2VyLmVycm9y
KA0KCQkJCQkiTm8gY29uZmlnIHN0b3JlZCBmb3IgYXNzZXQgb2YgdHlwZSAnIiArIGFzc2V0VHlw
ZSArICInLCB0cnlpbmcgdG8gcmVsb2FkIGRlZmF1bHQgY29uZmlnIGRpci4iKTsNCgkJCWxvYWRD
b25maWd1cmF0aW9uRnJvbURlZmF1bHRDb25maWdEaXIoKTsNCgkJCWpDb25maWcgPSBfY29uZmln
dXJhdGlvbnMuZ2V0KGFzc2V0VHlwZSk7DQoJCQlpZiAoakNvbmZpZyA9PSBudWxsKSB7DQoJCQkJ
bG9nZ2VyLmVycm9yKCJObyBjb25maWcgc3RvcmVkIGZvciBhc3NldCBvZiB0eXBlICciICsgYXNz
ZXRUeXBlICsgIicuIik7DQoJCQkJcmV0dXJuOw0KCQkJfQ0KCQl9DQoJCUpzb25WYWx1ZSBhc3Nl
dENvbmZpZyA9IGpDb25maWcuYXNPYmplY3QoKS5nZXQoYXNzZXRUeXBlKTsNCi8vCQlJRGF0YSBj
b25maWdEb2MgPSBwYXJzZUpzb24oYXNzZXRDb25maWcuYXNPYmplY3QoKSk7DQoJCUlEYXRhIGNv
bmZpZ0RvYyA9IHBhcnNlSnNvbihqQ29uZmlnLmFzT2JqZWN0KCkpOw0KCQlJRGF0YVV0aWwucHV0
KHBpcGVsaW5lQ3Vyc29yLCAiY29uZmlnIiwgY29uZmlnRG9jKTsNCgkJcGlwZWxpbmVDdXJzb3Iu
ZGVzdHJveSgpOw0KDQoJDQo=</value>
</Values>
