<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">stringToFile</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:0:required fileName</value>
    <value>[i] field:0:required data</value>
    <value>[i] field:0:optional append {"false","true"}</value>
    <value>[i] field:0:optional encoding</value>
  </array>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUNCklEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vy
c29yKCk7DQpTdHJpbmcJZmlsZU5hbWUgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKCBwaXBlbGluZUN1
cnNvciwgImZpbGVOYW1lIiApOw0KU3RyaW5nCWRhdGEgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKCBw
aXBlbGluZUN1cnNvciwgImRhdGEiICk7DQpTdHJpbmcJYXBwZW5kID0gSURhdGFVdGlsLmdldFN0
cmluZyggcGlwZWxpbmVDdXJzb3IsICJhcHBlbmQiICk7DQpTdHJpbmcJZW5jb2RpbmcgPSBJRGF0
YVV0aWwuZ2V0U3RyaW5nKCBwaXBlbGluZUN1cnNvciwgImVuY29kaW5nIiApOw0KcGlwZWxpbmVD
dXJzb3IuZGVzdHJveSgpOw0KDQppZiggZmlsZU5hbWUgPT0gbnVsbCB8fCBmaWxlTmFtZS5lcXVh
bHMoIiIpICkgew0KCXRocm93IG5ldyBTZXJ2aWNlRXhjZXB0aW9uKCJXeFV0aWxpdGllcy5zdHJp
bmdUb0ZpbGU6IGZpbGVOYW1lIG11c3Qgbm90IGJlIGVtcHR5LiIpOw0KfQ0KaWYoIGFwcGVuZCA9
PSBudWxsICkgew0KCWFwcGVuZCA9ICJmYWxzZSI7IA0KfQ0KaWYoICEoYXBwZW5kLmVxdWFsc0ln
bm9yZUNhc2UoInRydWUiKSB8fCBhcHBlbmQuZXF1YWxzSWdub3JlQ2FzZSgiZmFsc2UiKSApICkg
ew0KCXRocm93IG5ldyBTZXJ2aWNlRXhjZXB0aW9uKCJXeFV0aWxpdGllcy5zdHJpbmdUb0ZpbGU6
IGFwcGVuZCBtdXN0IGVpdGhlciBiZSAndHJ1ZScgb3IgJ2ZhbHNlJy4gSWYgbm90IHNldCwgZGVm
YXVsdCBpcyAnZmFsc2UnLiIpOw0KfQ0KYm9vbGVhbiBib29sQXBwZW5kID0gZmFsc2U7DQppZigg
YXBwZW5kLmVxdWFsc0lnbm9yZUNhc2UoInRydWUiKSApIHsNCglib29sQXBwZW5kID0gdHJ1ZTsN
Cn0NClByaW50V3JpdGVyIG91dCA9IG51bGw7IA0KdHJ5IHsNCiAgICBGaWxlIGZpbGUgPSBuZXcg
RmlsZShmaWxlTmFtZSk7DQogICAgRmlsZU91dHB1dFN0cmVhbSBmb3MgPSBuZXcgRmlsZU91dHB1
dFN0cmVhbShmaWxlLCBib29sQXBwZW5kICk7DQogICAgT3V0cHV0U3RyZWFtV3JpdGVyIG9zdyA9
IG51bGw7DQogICAgaWYoIGVuY29kaW5nICE9IG51bGwgKSB7DQogICAgCW9zdyA9IG5ldyBPdXRw
dXRTdHJlYW1Xcml0ZXIoZm9zLCBlbmNvZGluZyk7DQogICAgfSBlbHNlIHsNCgkgICAgb3N3ID0g
bmV3IE91dHB1dFN0cmVhbVdyaXRlcihmb3MpOw0KICAgIH0NCiAgICBvdXQgPSBuZXcgUHJpbnRX
cml0ZXIob3N3KTsNCiAgICBvdXQucHJpbnQoZGF0YSk7DQp9IGNhdGNoIChJT0V4Y2VwdGlvbiBl
KSB7DQogICAgdGhyb3cgbmV3IFNlcnZpY2VFeGNlcHRpb24oIld4VXRpbGl0aWVzLnN0cmluZ1Rv
RmlsZTogYW4gZXhjZXB0aW9uIG9jY3VyZWQgd2hlbiB0cnlpbmcgdG8gd3JpdGUgdG8gZmlsZSAn
IiArIGZpbGVOYW1lICsgIic6ICIgKyBlKTsNCn0gZmluYWxseSB7DQoJaWYoIG91dCAhPSBudWxs
ICkgew0KCQlvdXQuY2xvc2UoKTsNCgl9DQp9DQo=</value>
</Values>
