<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">loadConfigurationFile</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:0:required configFile</value>
    <value>[i] field:0:optional packageName</value>
  </array>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgcGlwZWxpbmVDID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQpTdHJpbmcgY29u
ZmlnRmlsZSA9IElEYXRhVXRpbC5nZXRTdHJpbmcocGlwZWxpbmVDLCAiY29uZmlnRmlsZSIpOw0K
U3RyaW5nIHBhY2thZ2VOYW1lID0gSURhdGFVdGlsLmdldFN0cmluZyhwaXBlbGluZUMsICJwYWNr
YWdlTmFtZSIpOw0KRmlsZSBjRmlsZSA9IG51bGw7DQoNCmlmKCBwYWNrYWdlTmFtZSAhPSBudWxs
ICYmICEiIi5lcXVhbHMocGFja2FnZU5hbWUpICkgew0KCUZpbGUgY29uZmlnRGlyID0gU2VydmVy
QVBJLmdldFBhY2thZ2VDb25maWdEaXIocGFja2FnZU5hbWUpOw0KCWlmKCAhY29uZmlnRGlyLmV4
aXN0cygpICkgew0KCQlsb2dnZXIuZXJyb3IoIkNvdWxkIG5vdCBsb2FkICciICsgY29uZmlnRmls
ZSArICInIGZyb20gY29uZmlnIGRpciBvZiBwYWNrYWdlICIgKyBwYWNrYWdlTmFtZSArICInOiBj
b25maWcgZGlyIGRvZXMgbm90IGV4aXN0LiIpOwkJCQkNCgkJcmV0dXJuOw0KCX0NCgljRmlsZSA9
IG5ldyBGaWxlKGNvbmZpZ0RpciwgY29uZmlnRmlsZSk7DQoJaWYoICFjRmlsZS5leGlzdHMoKSAp
IHsNCgkJbG9nZ2VyLmVycm9yKCJDb3VsZCBub3QgbG9hZCAnIiArIGNvbmZpZ0ZpbGUgKyAiJyBm
cm9tIGNvbmZpZyBkaXIgb2YgcGFja2FnZSAnIiArIHBhY2thZ2VOYW1lICsgIic6IGNvbmZpZyBm
aWxlIGRvZXMgbm90IGV4aXN0LiIpOwkJCQkNCgkJcmV0dXJuOw0KCX0NCn0gZWxzZSB7DQoJY0Zp
bGUgPSBuZXcgRmlsZShjb25maWdGaWxlKTsNCglpZiAoIWNGaWxlLmV4aXN0cygpKSB7DQoJCWxv
Z2dlci5lcnJvcigiQ291bGQgbm90IGxvYWQgJyIgKyBjb25maWdGaWxlICsgIjogY29uZmlnIGZp
bGUgZG9lcyBub3QgZXhpc3QgaW4gZGlyZWN0b3J5ICIgKyBuZXcgRmlsZSgiLiIpLmdldEFic29s
dXRlUGF0aCgpKTsJCQkJDQoJCXJldHVybjsNCgl9DQp9DQppZiggY0ZpbGUgIT0gbnVsbCApIHsN
Cglsb2dnZXIuZGVidWcoIkxvYWRpbmcgY29uZmlndXJhdGlvbiBmaWxlICIgKyBjRmlsZS5nZXRB
YnNvbHV0ZVBhdGgoKSk7DQoJYWRkQXNzZXRDb25maWd1cmF0aW9uKGNGaWxlKTsNCn0JCQkNCg==
</value>
</Values>
