<project name="wxplatformmonitoring" basedir="." default="installWxPlatformMonitoringPackage">
	

	<!-- use the build_default.properties file -->
	<property name="version" value="default" />
	
	<import file="build_internal.xml"/>
	<target name="createWxPlatformMonitoringBuild" description="Copy the WxPlatformMonitoring package to the target IntegrationServer, run jcode, copy back and store as zip in the build dir">
		<!--<antcall target="buildWxPlatformMonitoring" inheritall="true" inheritrefs="true">-->
		<antcall target="buildWxPlatformMonitoring">
			<param name="version" value="${version}"/>
		</antcall>
	</target>
	
	<target name="installWxPlatformMonitoringPackageAsSymLink" description="Create a symbolic link in the traget IS pointing to ./is_packages/WxPlatformMonitoring">
		<antcall target="installPackageAsSymLink">
			<param name="packageName" value="WxPlatformMonitoring" />
		</antcall>
	</target>
	
	<target name="installWxPlatformMonitoringPackage" depends="createWxPlatformMonitoringBuild" description="Copies the WxPlatformMonitoring package to the target IS's package directory and activates the packaage">
		<antcall target="distWxPlatformMonitoringPackage"></antcall>
	</target>
	
	
</project>