apply plugin: 'java'

repositories {
    mavenCentral()
	flatDir {
		dirs 'c:/SoftwareAG99/common/lib'
	}
}

sourceSets {
	main {
		java {
			srcDirs = ["src", "is_packages/WxPlatformMonitoring/code/source"]
		}
	}
}
configurations {
	compile {
		description = 'compile classpath'
		transitive = true
	}
	wxPackage {
		extendsFrom compile
	}
}

def WM_HOME="c:/SoftwareAG910"

dependencies {
	compile "com.eclipsesource.minimal-json:minimal-json:0.9.4"
	compile fileTree(dir: "${WM_HOME}/IntegrationServer/lib", includes: ["wm-isserver.jar"])
	compile fileTree(dir: "${WM_HOME}/common/lib", includes: ["wm-broker-acdl.jar",
		"wm-brokerclient.jar",
		"wm-isclient.jar" ,
		"wm-jmsadmin.jar" ,
		"wm-jmsclient.jar" ,
		"wm-jmsnaming.jar" ,
		"wm-isserver.jar" ,
		"terracotta-toolkit-runtime-ee.jar", 
		"ehcache-ee.jar"  ,
		"nClient.jar"  ,
		"nAdminAPI.jar" , 
		"nJMS.jar" ,
		"ehcache-ee-terracotta-client-all.jar"])
	compile fileTree(dir: "${WM_HOME}/common/lib/ext", includes: ["log4j.jar",
		"enttoolkit.jar",
		"slf4j-api.jar",
		"ant.jar",
		"ant-launcher.jar"])
}


task getDeps(type: Copy) {
	from configurations.wxPackage
	into 'is_packages/WxPlatformMonitoring/code/jars'
}