buildscript {
	repositories {
		mavenCentral()
		jcenter()
		maven {
			url "https://plugins.gradle.org/m2/"
		}
	}
	dependencies { 
		classpath "org.ajoberstar:gradle-git:1.7.2"
	}
}

apply plugin: 'java'
apply plugin: 'groovy'
apply plugin: 'distribution'
apply plugin: 'base'
apply plugin: 'maven'
apply plugin: "org.ajoberstar.grgit"


Properties props = new Properties()
//props.load(new FileInputStream(new File(projectDir, "build_912.properties")))
props.load(new FileInputStream(new File(projectDir, "build_101.properties")))

// dummy version number necessary for grggit
version = "1.1.0-SNAPSHOT"
group = "com.softwareag.wx.platformMonitoring"
archivesBaseName='WxPlatformMonitoringDist'
def packages = ['WxPlatformMonitoring', 'WxPlatformMonitoring_Test']

tasks.distTar.enabled = false

ext {
	// Open the Git repository in the current directory.
	git = org.ajoberstar.grgit.Grgit.open(file('.'))
	// Get commit id of HEAD.
	// revision = git.head().id
	// Alternative is using abbreviatedId of head() method.
	revision = grgit.head().abbreviatedId
	buildNumber = grgit.head().abbreviatedId
}

distributions {
	wxplatformmon {
		baseName = name
		version = version
		contents {
		}
	}
}

// read the labcase password of user waa from the file labcase.pwd
def getLabcasePassword() {
	def file = new File(projectDir, 'labcase.pwd')
	if( file.exists() ) {
		return file.text
	} else {
		def msg = "> Password file 'labcase.pwd' does not exist in root dir " + new File(".").getAbsolutePath()
		println msg
		throw new RuntimeException(mgs)
	}
}


// copy the packages from the is_packages folder to the tmp folder
task copyPackages() {
	doLast {
		println "> Copying package from is_packages to tmp"
		copy {
			from "is_packages"
			into "tmp"
		}
	}
}

// dynamically create a task for each pacakge to manipulate the manifest.v3 file
def manifesto(packageName) {
	return tasks.create("manifest${packageName}") {
		doLast {
			def mv3 = new File(projectDir, "tmp/${packageName}/manifest.v3")
			def xml = new XmlSlurper().parse(mv3)
			def nodes = xml.'**'.findAll { node ->
				if( node.@'name' == "build" ) {
					node.replaceBody "${buildNumber} (${version})"
				}
				if( node.@'name' == "version" ) {
					node.replaceBody version
				}
			}
			mv3.withWriter { out ->
				groovy.xml.XmlUtil.serialize(xml, out)
			}
			println "> Created manifest.v3 for package ${packageName} with version $version"
		}
	}
}

// task rule for dynamically creating a task for each zip to create
tasks.addRule('Pattern: zipPackage<PACKAGE>') { String taskName ->
	if (taskName.startsWith('zipPackage')) {
		// get the package name from the task name
		def packageName = (taskName - 'zipPackage')
		task(taskName, dependsOn: manifesto(packageName), type: Zip) {
			println "> Creating zip for package ${packageName}..."
			archiveName "${packageName}.zip"
			from "tmp/${packageName}"
			destinationDir file("src/wxplatformmon/dist")
		}
	}
}
// zip all packages
task zipPackages {
	dependsOn << packages.collect { packageName -> "zipPackage${packageName}" }
}

// wxplatformmonDistZip is automatically created by the Distribution plugin for the configuration wxplatformmon
wxplatformmonDistZip.dependsOn zipPackages

task createReleaseNotes(dependsOn: classes) {
	doLast {
		javaexec {
			println "> Creating release notes"
			main = 'com.softwareag.wx.restServices.utils.labcase.ReleaseNotes'
			classpath = sourceSets.main.runtimeClasspath
			args('-versionId', labcaseReleaseVersion)
			args('-filePath', './tmp/releaseNotes.txt')
		}
	}
}

// copy the release notes to the packages and in the dist folder
task copyReleaseNote(dependsOn: createReleaseNotes) {
	doLast {
		['tmp/WxPlatformMonitoring/resources', 'tmp/WxPlatformMonitoring_Test/resources', 'src/wxplatformmon/dist'].each { dest ->
			println "> Copy releaseNotes into $dest with version $version"
			copy {
				from ("tmp/releaseNotes.txt")  {
					filter(org.apache.tools.ant.filters.ReplaceTokens, tokens: ["version": project.version.toString()])
				}
				into(dest)
				rename { String fileName -> "releaseNotes_${project.version.toString()}.txt" }
			}
		}
	}
}

// remove old data
task cleanup {
	doLast {
		delete "tmp"
		delete "src/dist/wxplatformmon"
	}
}

configurations {
	wxplatformmon
	compile {
		description = 'compile classpath'
		transitive = true
	}
	// wxplatformmonjars is just a "dummy" configuration for the dependencies section and the pom generation
	wxplatformmonjars {
//		extendsFrom compile
	}
}

artifacts { // define that the configuration wxplatformmon uses the output from distZip as the artifacts
	'wxplatformmon' distZip }


task uploadRelease(type: Upload) {
	configuration = configurations.wxplatformmon
	repositories {
		mavenDeployer {
			configuration = configurations.wxplatformmon
			def DAV =  [
				server: "labcase.softwareag.com",
				root: "dav",
				user: "waa",
				pass: getLabcasePassword()
			]
			def labcasePath = "DE/GCS/GCS/wxplatformmon/"
			if(getProjectVersion().endsWith('SNAPSHOT')) {
				labcasePath = labcasePath + "snapshots"
			} else if(!getProjectVersion().endsWith('RELEASE')) {
				labcasePath = labcasePath + "release"
			} else {
				throw new RuntimeException("Could not determine version for " + getProjectVersion());
			}
			repository(url: "dav:https://${DAV.server}/${DAV.root}/${labcasePath}") {
				println "> uploading to release repo"
				authentication(userName: DAV.user, password: DAV.pass)
			}
			uniqueVersion = false
			pom.project {
				licenses {
					license {
						name 'Software AG GCS - wM Consulting Tools - WxPlatformMonitoring'
						url 'https://labcase.softwareag.com/projects/primetoolsutilities/wiki/Home'
						distribution 'manual'
					}
				}
				organization {
					name 'Software AG GCS'
					url 'https://labcase.softwareag.com/projects/primetoolsutilities'
				}
				developers {
					developer {
						id 'waa'
						name 'Henning Waack'
						organization = 'Software AG GCS'
						roles {
							role 'Project Manager'
							role 'Architect'
							role 'Developer'
						}
					}
				}
			}
			// remove alll dependencies, should be set in sub projects (does not work though)
			pom.scopeMappings.with {
				mappings.clear()
				addMapping(300, configurations.wxplatformmonjars, 'wxplatformmonjars')
			}
		}
	}
}


task releaseActions(dependsOn: [cleanup, copyPackages, copyReleaseNote, wxplatformmonDistZip, install, uploadRelease]) {
	doLast {  
		println "We build the distribution ZIP with version '$version'."  
	}
}
task releaseSnapshot(dependsOn: [releaseActions]) {
	doLast {
		  println "We build the distribution ZIP with version '$version'."  
	}
}
task releaseIt (dependsOn: [releaseActions]) {
	doLast {
		 println 'We release now.' 
	}
}


sourceSets {
	main {
		java {
			srcDirs = ["is_packages/WxPlatformMonitoring/code/source"]
		}
		java.outputDir = file("is_packages/WxPlatformMonitoring/code/classes")
		groovy { srcDirs = ['src/main/groovy']}
	}
}

repositories {
	mavenCentral()
	jcenter()
}


packages.each { packageName ->
	tasks.create(name: "createSymLinkFor${packageName}", type: Exec) {
		commandLine 'cmd', '/c', 'MKLINK'
		def link = props['is.home'] + "/packages/" + packageName
		def resource = file("./is_packages/$packageName").getAbsolutePath()
		args '/D', '"' + link + '"', '"' + resource + '"'
		ignoreExitValue true
		doLast { println "> Created symlink for package $packageName" }
	}
}


task jcodeMakeAll(type: Exec, dependsOn: "distributeLocal") {
	workingDir "${props['is.home']}/bin"
	commandLine 'cmd', '/c', "${props['is.home']}/bin/jcode.bat"
	args 'makeall', 'WxPlatformMonitoring'
	ignoreExitValue true
	doLast {
		ant.get(src: "http://" + props['is.host'] + ":" + props['is.port'] + "/WmRoot/package-list.dsp?action=reload&package=WxPlatformMonitoring", dest: "", username: "Administrator", password: "manage", verbose: "true")
		ant.delete(file: "package-list.dsp")
		println "> Executed jcode for WxPlatformMonitoring"
	}
}


/**
 * install packages as symbolic links into IntegrationServer's packages dir
 */
task distributeLocal {
	dependsOn classes
	dependsOn << packages.collect { "createSymLinkFor$it" }
	doLast {
		// copy relevant jars to the jar dir
		copy {
			// create the jar with the test builder
			// get the jar references by the testbuilder configuration
			from project.configurations.wxplatformmonjars
			into ('is_packages/WxPlatformMonitoring/code/jars/')
		}
		ant.get(src: "http://" + props['is.host'] + ":" + props['is.port'] + "/invoke/wm.server.packages.adminui/packageActivate?action=activate&package=WxPlatformMonitoring", dest: "", username: "Administrator", password: "manage", verbose: "true")
		ant.get(src: "http://" + props['is.host'] + ":" + props['is.port'] + "/invoke/wm.server.packages.adminui/packageActivate?action=activate&package=WxPlatformMonitoring_Test", dest: "", username: "Administrator", password: "manage", verbose: "true")
		ant.delete(file: "packageActivate")
	}
}


dependencies {
	// from local file system
	compile fileTree(dir: "is_packages/WxPlatformMonitoring/code/jars", include: '*.jar')
	compile fileTree(dir: props["wm.home"] + "/IntegrationServer/lib", includes: ["wm-isserver.jar"])
	compile fileTree(dir: props["wm.home"] + "/common/lib", includes: ["wm-broker-acdl.jar",
		"wm-brokerclient.jar",
		"wm-isclient.jar" ,
		"wm-jmsadmin.jar" ,
		"wm-jmsclient.jar" ,
		"wm-jmsnaming.jar" ,
		"wm-isserver.jar" ,
		"terracotta-toolkit-runtime-ee.jar",
		"ehcache-ee.jar"  ,
		"nClient.jar"  ,
		"nAdminAPI.jar" ,
		"nJMS.jar" ,
		"ehcache-ee-terracotta-client-all.jar"])
	compile fileTree(dir: props["wm.home"] + "/common/lib/ext", includes: ["log4j.jar",
		"enttoolkit.jar",
		"slf4j-api.jar",
		"ant.jar",
		"ant-launcher.jar"])
	compile fileTree(dir: props["wm.home"] + "/common/lib/glassfish", includes: ["gf.javax.jms.jar"])
	
	compile group: 'org.codehaus.groovy', name: 'groovy-all', version: '2.4.12'
	compile 'log4j:log4j:1.2.17'
	compile group: 'org.apache.ivy', name: 'ivy', version: '2.4.0'
	compile group: 'org.apache.httpcomponents', name: 'httpcore', version: '4.3.3'
	compile group: 'org.codehaus.groovy.modules.http-builder', name: 'http-builder', version: '0.5.0'
	compile group: 'org.apache.ant', name: 'ant', version: '1.9.8'
	compile group: 'org.apache.ant', name: 'ant-launcher', version: '1.9.8'
	compile group: 'commons-cli', name: 'commons-cli', version: '1.4'
	wxplatformmon "org.apache.maven.wagon:wagon-webdav:1.0-beta-2" // necessary for webdav upload
	// dependencies which are already contained in the IS Package, just as a reference
	wxplatformmonjars group: 'commons-logging', name: 'commons-logging', version: '1.2'
	wxplatformmonjars group: 'com.eclipsesource.minimal-json', name: 'minimal-json', version: '0.9.4'
}

def getProjectVersion() {
	def v = project.version - "-SNAPSHOT"
	println "returning version " + v + "  $project.version"
	return v
}

def getReleaseVersion() {
	return project.version
}


task getDeps(type: Copy) {
	from configurations.wxplatformmonjars
	into 'is_packages/WxPlatformMonitoring/code/jars'
}