<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">getQueuedElements</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:0:required RNAME</value>
    <value>[i] field:0:required queueName</value>
    <value>[o] field:0:required outstandingEvents</value>
    <value>[o] record:1:required sharedDurableOutstandingEvents</value>
    <value>[o] - field:0:required outstandingEvents</value>
    <value>[o] - field:0:required namedObject</value>
    <value>[o] field:0:required outstandingEventsSharedDurableMax</value>
  </array>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">dHJ5IHsKCQoJLy8gcGlwZWxpbmUKCUlEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yID0gcGlwZWxp
bmUuZ2V0Q3Vyc29yKCk7CglTdHJpbmcJUk5BTUUgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKCBwaXBl
bGluZUN1cnNvciwgIlJOQU1FIiApOwoJU3RyaW5nCXF1ZXVlTmFtZSA9IElEYXRhVXRpbC5nZXRT
dHJpbmcoIHBpcGVsaW5lQ3Vyc29yLCAicXVldWVOYW1lIiApOwoJCglpZiggUk5BTUUgPT0gbnVs
bCB8fCAiIi5lcXVhbHMoUk5BTUUpICkgIHsKCQl0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbigi
Uk5BTUUgbXVzdCBub3QgYmUgZW1wdHkuIFByb3ZpZGUgbGlrZTogJ25zcDovL2hvc3Q6cG9ydCcu
Iik7Cgl9CglpZiggcXVldWVOYW1lID09IG51bGwgfHwgIiIuZXF1YWxzKHF1ZXVlTmFtZSkgKSB7
CgkJdGhyb3cgbmV3IFNlcnZpY2VFeGNlcHRpb24oInF1ZXVlTmFtZSBtdXN0IG5vdCBiZSBudWxs
LiIpOwoJfQoJCgluU2Vzc2lvbkF0dHJpYnV0ZXMgbnNhPW5ldyBuU2Vzc2lvbkF0dHJpYnV0ZXMo
Uk5BTUUpOwoJblNlc3Npb24gICAgICBteVNlc3Npb24gPSBuU2Vzc2lvbkZhY3RvcnkuY3JlYXRl
KG5zYSk7CglteVNlc3Npb24uaW5pdCgpOwoJCgluQ2hhbm5lbEF0dHJpYnV0ZXMgYXR0cmliID0g
bmV3IG5DaGFubmVsQXR0cmlidXRlcygpOwogICAgYXR0cmliLnNldE5hbWUocXVldWVOYW1lKTsK
ICAgIGNvbS5wY2JzeXMubmlydmFuYS5jbGllbnQubkZpbmRSZXN1bHRbXSBmaW5kUmVzdWx0ID0g
bXlTZXNzaW9uLmZpbmQobmV3IG5DaGFubmVsQXR0cmlidXRlc1tdIHthdHRyaWJ9KTsKICAgIGlm
KCBmaW5kUmVzdWx0Lmxlbmd0aCA9PSAwICkgewogICAgCXRocm93IG5ldyBTZXJ2aWNlRXhjZXB0
aW9uKCJRZXVldSIgKyBxdWV1ZU5hbWUrICIgd2FzIG5vdCBmb3VuZCBvbiByZWFsbSAiICsgUk5B
TUUpOwogICAgfQogICAgaWYoIGZpbmRSZXN1bHRbMF0uaXNDaGFubmVsKCkgKSB7CiAgICAJLy8g
aWYgaXQgaXMgYSBjaGFubmVsLCB0aGVuIGl0IGlzIGEgam1zIHRvcGljCiAgICAJSURhdGFVdGls
LnB1dCggcGlwZWxpbmVDdXJzb3IsICJjaGFubmVsTmFtZSIsIHF1ZXVlTmFtZSk7CiAgICAJZ2V0
UXVldWVkRWxlbWVudHNDaGFubmVsKHBpcGVsaW5lKTsKICAgIH0gZWxzZSBpZiggZmluZFJlc3Vs
dFswXS5pc1F1ZXVlKCkgKSB7CiAgICAJLy8gdGhpcyBpcyBhIGptcyBxdWV1ZQogICAgCWdldFF1
ZXVlZEVsZW1lbnRzSm1zUXVldWUocGlwZWxpbmUpOwogICAgfSBlbHNlIHsKICAgIAl0aHJvdyBu
ZXcgU2VydmljZUV4Y2VwdGlvbigiUXVldWUgIiArIHF1ZXVlTmFtZSArICIgb24gcmVhbG0gIiAr
IFJOQU1FICsgIiBpcyBuZWl0aGVyIHF1ZXVlIG5vciBjaGFubmVsLiIpOwogICAgfQogICAgcGlw
ZWxpbmVDdXJzb3IuZGVzdHJveSgpOwoJCn0gY2F0Y2ggKEV4Y2VwdGlvbiBlKSB7CgkvLyBUT0RP
IEF1dG8tZ2VuZXJhdGVkIGNhdGNoIGJsb2NrCgllLnByaW50U3RhY2tUcmFjZSgpOwoJdGhyb3cg
bmV3IFNlcnZpY2VFeGNlcHRpb24oZSk7Cn0KCgkK</value>
</Values>
