<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">getQueuedElementsJmsQueue</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:0:required RNAME</value>
    <value>[i] field:0:required queueName</value>
    <value>[o] field:0:required outstandingEvents</value>
    <value>[o] field:0:required queueStorageSize</value>
  </array>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">dHJ5IHsKCQoJLy8gcGlwZWxpbmUKCUlEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yID0gcGlwZWxp
bmUuZ2V0Q3Vyc29yKCk7CglTdHJpbmcJUk5BTUUgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKCBwaXBl
bGluZUN1cnNvciwgIlJOQU1FIiApOwoJU3RyaW5nCXF1ZXVlTmFtZSA9IElEYXRhVXRpbC5nZXRT
dHJpbmcoIHBpcGVsaW5lQ3Vyc29yLCAicXVldWVOYW1lIiApOwoJCglpZiggUk5BTUUgPT0gbnVs
bCB8fCAiIi5lcXVhbHMoUk5BTUUpICkgIHsKCQl0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbigi
Uk5BTUUgbXVzdCBub3QgYmUgZW1wdHkuIFByb3ZpZGUgbGlrZTogJ25zcDovL2hvc3Q6cG9ydCcu
Iik7Cgl9CglpZiggcXVldWVOYW1lID09IG51bGwgfHwgIiIuZXF1YWxzKHF1ZXVlTmFtZSkgKSB7
CgkJdGhyb3cgbmV3IFNlcnZpY2VFeGNlcHRpb24oInF1ZXVlTmFtZSBtdXN0IG5vdCBiZSBudWxs
LiIpOwoJfQoJCgluU2Vzc2lvbkF0dHJpYnV0ZXMgbnNhPW5ldyBuU2Vzc2lvbkF0dHJpYnV0ZXMo
Uk5BTUUpOwoJblNlc3Npb24gICAgICBteVNlc3Npb24gPSBuU2Vzc2lvbkZhY3RvcnkuY3JlYXRl
KG5zYSk7CglteVNlc3Npb24uaW5pdCgpOwoKCW5DaGFubmVsQXR0cmlidXRlcyBhdHRyaWIgPSBu
ZXcgbkNoYW5uZWxBdHRyaWJ1dGVzKCk7CiAgICBhdHRyaWIuc2V0TmFtZShxdWV1ZU5hbWUpOwog
ICAgblF1ZXVlIHF1ZXVlID0gbXlTZXNzaW9uLmZpbmRRdWV1ZShhdHRyaWIpOwogICAgY29tLnBj
YnN5cy5uaXJ2YW5hLmNsaWVudC5uUXVldWVEZXRhaWxzIGRldGFpbHMgPSBxdWV1ZS5nZXREZXRh
aWxzKCk7CiAgICBJRGF0YVV0aWwucHV0KHBpcGVsaW5lQ3Vyc29yLCAib3V0c3RhbmRpbmdFdmVu
dHMiLCBkZXRhaWxzLmdldE5vT2ZFdmVudHMoKSArICIiKTsKICAgIElEYXRhVXRpbC5wdXQocGlw
ZWxpbmVDdXJzb3IsICJxdWV1ZVN0b3JhZ2VTaXplIiwgZGV0YWlscy5nZXRUb3RhbE1lbW9yeVNp
emUoKSArICIiKTsKICAgIHBpcGVsaW5lQ3Vyc29yLmRlc3Ryb3koKTsKCQp9IGNhdGNoIChFeGNl
cHRpb24gZSkgewoJLy8gVE9ETyBBdXRvLWdlbmVyYXRlZCBjYXRjaCBibG9jawoJZS5wcmludFN0
YWNrVHJhY2UoKTsKCXRocm93IG5ldyBTZXJ2aWNlRXhjZXB0aW9uKGUpOwp9CgoJCg==</value>
</Values>
