<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">getFile</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:0:required filename</value>
    <value>[i] field:0:optional context</value>
    <value>[i] field:0:required dir</value>
    <value>[i] field:0:optional encoding</value>
    <value>[o] field:0:required stringOut</value>
  </array>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUNCklEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vy
c29yKCk7DQpTdHJpbmcJZmlsZW5hbWUgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKCBwaXBlbGluZUN1
cnNvciwgImZpbGVuYW1lIiApOw0KU3RyaW5nCWNvbnRleHQgPSBJRGF0YVV0aWwuZ2V0U3RyaW5n
KCBwaXBlbGluZUN1cnNvciwgImNvbnRleHQiICk7DQpTdHJpbmcJZGlyID0gSURhdGFVdGlsLmdl
dFN0cmluZyggcGlwZWxpbmVDdXJzb3IsICJkaXIiICk7DQpTdHJpbmcJZW5jb2RpbmcgPSBJRGF0
YVV0aWwuZ2V0U3RyaW5nKCBwaXBlbGluZUN1cnNvciwgImVuY29kaW5nIiApOw0KcGlwZWxpbmVD
dXJzb3IuZGVzdHJveSgpOw0KDQppZiggZmlsZW5hbWUgPT0gbnVsbCApIHsNCgl0aHJvdyBuZXcg
U2VydmljZUV4Y2VwdGlvbigiRmlsZW5hbWUgbXVzdCBiZSBwcm92aWRlZC4iKTsNCn0NCmlmKCBj
b250ZXh0ID09IG51bGwgKSB7DQoJY29udGV4dCA9ICJkZWZhdWx0IjsNCn0NCmlmKCBkaXIgPT0g
bnVsbCApIHsNCgl0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbigiRGlyZWN0b3J5IG11c3QgYmUg
cHJvdmlkZWQuIik7DQp9DQoNCkZpbGUgYmFzZURpciA9IG5ldyBGaWxlKGRpcik7DQppZiggYmFz
ZURpci5leGlzdHMoKSAmJiAhYmFzZURpci5pc0RpcmVjdG9yeSgpICkgew0KCXRocm93IG5ldyBT
ZXJ2aWNlRXhjZXB0aW9uKCJQcm92aWRlIGEgdmFsaWQgZGlyZWN0b3J5IHdoaWNoIGV4aXN0cy4i
KTsNCn0gZWxzZSBpZiggIWJhc2VEaXIuZXhpc3RzKCkgKSB7DQoJYmFzZURpci5ta2RpcigpOw0K
fQ0KDQpGaWxlIGNvbnRleHREaXIgPSBuZXcgRmlsZShiYXNlRGlyLCBjb250ZXh0KTsNCmlmKCAh
Y29udGV4dERpci5leGlzdHMoKSApIHsNCgljb250ZXh0RGlyLm1rZGlyKCk7DQp9DQoNCkZpbGUg
dGFyZ2V0RmlsZSA9IG5ldyBGaWxlKGNvbnRleHREaXIsIGZpbGVuYW1lKTsNCmlmKCAhdGFyZ2V0
RmlsZS5leGlzdHMoKSApIHsNCglyZXR1cm47DQp9DQoNClN0cmluZ0J1ZmZlciBmaWxlRGF0YSA9
IG5ldyBTdHJpbmdCdWZmZXIoKTsNCkJ1ZmZlcmVkUmVhZGVyIHJlYWRlciA9IG51bGw7DQp0cnkg
ew0KCWlmKCBlbmNvZGluZyAhPSBudWxsICkgew0KCQlyZWFkZXIgPSBuZXcgQnVmZmVyZWRSZWFk
ZXIobmV3IElucHV0U3RyZWFtUmVhZGVyKG5ldyBGaWxlSW5wdXRTdHJlYW0odGFyZ2V0RmlsZSks
IGVuY29kaW5nKSk7DQoJfSBlbHNlIHsNCgkJcmVhZGVyID0gbmV3IEJ1ZmZlcmVkUmVhZGVyKG5l
dyBGaWxlUmVhZGVyKHRhcmdldEZpbGUpKTsNCgl9DQoJY2hhcltdIGJ1ZiA9IG5ldyBjaGFyWzEw
MjRdOw0KCWludCBudW1SZWFkPTA7DQoJd2hpbGUoKG51bVJlYWQ9cmVhZGVyLnJlYWQoYnVmKSkg
IT0gLTEpew0KCQlTdHJpbmcgcmVhZERhdGEgPSBTdHJpbmcudmFsdWVPZihidWYsIDAsIG51bVJl
YWQpOw0KCQlmaWxlRGF0YS5hcHBlbmQocmVhZERhdGEpOw0KCX0NCn0gY2F0Y2goIEZpbGVOb3RG
b3VuZEV4Y2VwdGlvbiBmbmZlICkgew0KCXRocm93IG5ldyBTZXJ2aWNlRXhjZXB0aW9uKCJFeGNl
cHRpb24gd2hlbiByZWFkaW5nIGZpbGUgIiArIHRhcmdldEZpbGUgKyAiOiAiICsgZm5mZSk7DQp9
IGNhdGNoKCBJT0V4Y2VwdGlvbiBpb2UgKSAgew0KCXRocm93IG5ldyBTZXJ2aWNlRXhjZXB0aW9u
KCJFeGNlcHRpb24gd2hlbiByZWFkaW5nIGZpbGUgIiArIHRhcmdldEZpbGUgKyAiOiAiICsgaW9l
KTsNCn0gZmluYWxseSB7DQoJdHJ5IHsNCglyZWFkZXIuY2xvc2UoKTsNCgl9IGNhdGNoKCBJT0V4
Y2VwdGlvbiBlICkgew0KCQkvLyBpZ25vcmUNCgl9DQp9DQpTdHJpbmcgc3RyaW5nT3V0ID0gZmls
ZURhdGEudG9TdHJpbmcoKTsNCklEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yXzEgPSBwaXBlbGlu
ZS5nZXRDdXJzb3IoKTsNCklEYXRhVXRpbC5wdXQoIHBpcGVsaW5lQ3Vyc29yXzEsICJzdHJpbmdP
dXQiLCBzdHJpbmdPdXQgKTsNCnBpcGVsaW5lQ3Vyc29yXzEuZGVzdHJveSgpOw0KCQ0K</value>
</Values>
