
artifact.repo.url.base=http://cdfield.eur.ad.sag:8082/artifactory
#artifact.repo.url.primeTools.release=${artifact.repo.url.base}/primetools-release-local
artifact.repo.url.primeTools.snapshot=${artifact.repo.url.base}/cco-digitization-snapshot-local



package.name=WxLicenseCheck
package.version.major=1
package.version.minor=0
package.version.patch=0
package.version=${package.version.major}.${package.version.minor}
#.${package.version.patch}


# Duplicates in format that works with shell execution
PKG_NAME=${package.name}
PKG_VERSION=${package.version}
webMethods.package.name=${PKG_NAME}
package.version.number=${PKG_VERSION}