<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">defaultExtendedSettingsPropertyResolver</value>
  <value name="spec">wx.platformMonitoring.impl.internal.propertyResolver:propertyResolverSpecification</value>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUKSURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRDdXJz
b3IoKTsKU3RyaW5nCXByb3BlcnR5TmFtZSA9IElEYXRhVXRpbC5nZXRTdHJpbmcoIHBpcGVsaW5l
Q3Vyc29yLCAicHJvcGVydHlOYW1lIiApOwoJCQkJCi8vIG91dHB1dApJRGF0YSAJb3V0cHV0ID0g
SURhdGFGYWN0b3J5LmNyZWF0ZSgpOwp0cnl7CglvdXRwdXQgPSBTZXJ2aWNlLmRvSW52b2tlKCAi
cHViLnV0aWxzIiwgImdldFNlcnZlclByb3BlcnR5IiwgcGlwZWxpbmUgKTsKfWNhdGNoKCBFeGNl
cHRpb24gZSl7Cgl0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbigiQ291bGQgbm90IHJlc29sdmUg
cHJvZXBydHkgIiArIHByb3BlcnR5TmFtZSArICIgdXNpbmcgZGVmYXVsdCBwcm9wZXJ0eSByZXNv
bHZlcjoiICArIGUpOwp9CklEYXRhQ3Vyc29yIG91dHB1dEN1cnNvciA9IG91dHB1dC5nZXRDdXJz
b3IoKTsKU3RyaW5nCXByb3BlcnR5VmFsdWUgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKCBvdXRwdXRD
dXJzb3IsICJwcm9wZXJ0eVZhbHVlIiApOwpvdXRwdXRDdXJzb3IuZGVzdHJveSgpOwoKSURhdGFV
dGlsLnB1dCggcGlwZWxpbmVDdXJzb3IsICJwcm9wZXJ0eVZhbHVlIiwgcHJvcGVydHlWYWx1ZSAp
OwpwaXBlbGluZUN1cnNvci5kZXN0cm95KCk7CgkK</value>
</Values>
