<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">getQueuedElementsChannel</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:0:required RNAME</value>
    <value>[i] field:0:required channelName</value>
    <value>[o] field:0:required outstandingEvents</value>
    <value>[o] record:1:required sharedDurableOutstandingEvents</value>
    <value>[o] - field:0:required outstandingEvents</value>
    <value>[o] - field:0:required namedObject</value>
    <value>[o] field:0:required outstandingEventsSharedDurableMax</value>
  </array>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">dHJ5IHsNCgkNCgkvLyBwaXBlbGluZQ0KCUlEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yID0gcGlw
ZWxpbmUuZ2V0Q3Vyc29yKCk7DQoJU3RyaW5nCVJOQU1FID0gSURhdGFVdGlsLmdldFN0cmluZygg
cGlwZWxpbmVDdXJzb3IsICJSTkFNRSIgKTsNCglTdHJpbmcJY2hhbm5lbE5hbWUgPSBJRGF0YVV0
aWwuZ2V0U3RyaW5nKCBwaXBlbGluZUN1cnNvciwgImNoYW5uZWxOYW1lIiApOw0KCQ0KCWlmKCBS
TkFNRSA9PSBudWxsIHx8ICIiLmVxdWFscyhSTkFNRSkgKSAgew0KCQl0aHJvdyBuZXcgU2Vydmlj
ZUV4Y2VwdGlvbigiUk5BTUUgbXVzdCBub3QgYmUgZW1wdHkuIFByb3ZpZGUgbGlrZTogJ25zcDov
L2hvc3Q6cG9ydCcuIik7DQoJfQ0KCWlmKCBjaGFubmVsTmFtZSA9PSBudWxsIHx8ICIiLmVxdWFs
cyhjaGFubmVsTmFtZSkgKSB7DQoJCXRocm93IG5ldyBTZXJ2aWNlRXhjZXB0aW9uKCJjaGFubmVs
TmFtZSBtdXN0IG5vdCBiZSBudWxsLiIpOw0KCX0NCgkNCgluU2Vzc2lvbkF0dHJpYnV0ZXMgbnNh
PW5ldyBuU2Vzc2lvbkF0dHJpYnV0ZXMoUk5BTUUpOw0KCW5TZXNzaW9uICAgICAgbXlTZXNzaW9u
ID0gblNlc3Npb25GYWN0b3J5LmNyZWF0ZShuc2EpOw0KCW15U2Vzc2lvbi5pbml0KCk7DQoJDQoJ
bkNoYW5uZWxBdHRyaWJ1dGVzIGF0dHJpYiA9IG5ldyBuQ2hhbm5lbEF0dHJpYnV0ZXMoKTsNCiAg
ICBhdHRyaWIuc2V0TmFtZShjaGFubmVsTmFtZSk7DQogICAgbkNoYW5uZWwgY2hhbm5lbCA9IG15
U2Vzc2lvbi5maW5kQ2hhbm5lbChhdHRyaWIpOw0KICAgIC8vIGNoZWNrIGZvciBzaGFyZWQgZHVy
YWJsZQ0KDQogICAgaWYoIGNoYW5uZWwuZ2V0RHVyYWJsZU1hbmFnZXIoKS5nZXRBbGwoKS5sZW5n
dGggIT0gMCApIHsJCSAgICANCiAgICAJLyoNCiAgICAJICogQSBzdGFuZGFyZCB3TSBtZXNzYWdp
bmcgdHJpZ2dlciBoYXMgYSBzaGFyZWQgZHVyYWJsZSBjb25uZWN0aW9uIGFuZCBkb2VzICJjb25j
dXJyZW50IiBwcm9jZXNzaW5nLg0KICAgIAkgKiBGb3Igc3VjaCBhIHRyaWdnZXIgaGlkZGVuIHF1
ZXVlcyBhcmUgY3JlYXRlZCwgd2hpY2ggYXJlIE5hbWVkIE9iamVjdHMgaW4gVU0uIA0KICAgIAkg
Ki8NCiAgICAJSURhdGFbXSBzaGFyZWREdXJhYmxlT3V0c3RhbmRpbmdFdmVudHMgPSBuZXcgSURh
dGFbY2hhbm5lbC5nZXREdXJhYmxlTWFuYWdlcigpLmdldEFsbCgpLmxlbmd0aF07DQogICAgCWxv
bmcgbWF4ID0gMDsNCiAgICAJbk5hbWVkT2JqZWN0W10gbmFtZWRPYmplY3RzID0gY2hhbm5lbC5n
ZXREdXJhYmxlTWFuYWdlcigpLmdldEFsbCgpOw0KICAgIAlmb3IoIGludCBpPTA7IGk8c2hhcmVk
RHVyYWJsZU91dHN0YW5kaW5nRXZlbnRzLmxlbmd0aDsgaSsrICkgew0KICAgIAkJbk5hbWVkT2Jq
ZWN0IG5vID0gbmFtZWRPYmplY3RzW2ldOw0KICAgIAkJc2hhcmVkRHVyYWJsZU91dHN0YW5kaW5n
RXZlbnRzW2ldID0gSURhdGFGYWN0b3J5LmNyZWF0ZSgpOw0KICAgIAkJSURhdGFDdXJzb3Igc2hh
cmVkRHVyYWJsZU91dHN0YW5kaW5nRXZlbnRzQyA9IHNoYXJlZER1cmFibGVPdXRzdGFuZGluZ0V2
ZW50c1tpXS5nZXRDdXJzb3IoKTsNCiAgICAJCWxvbmcgb3V0c3RhbmRpbmdFdmVudHMgPSBuby5n
ZXRPdXRzdGFuZGluZ0V2ZW50cygpOw0KICAgIAkJSURhdGFVdGlsLnB1dChzaGFyZWREdXJhYmxl
T3V0c3RhbmRpbmdFdmVudHNDLCAib3V0c3RhbmRpbmdFdmVudHMiLCBvdXRzdGFuZGluZ0V2ZW50
cyArICIiKTsNCiAgICAJCUlEYXRhVXRpbC5wdXQoc2hhcmVkRHVyYWJsZU91dHN0YW5kaW5nRXZl
bnRzQywgIm5hbWVkT2JqZWN0Iiwgbm8uZ2V0TmFtZSgpKTsNCiAgICAJCXNoYXJlZER1cmFibGVP
dXRzdGFuZGluZ0V2ZW50c0MuZGVzdHJveSgpOw0KICAgIAkJaWYoIG1heCA8IG91dHN0YW5kaW5n
RXZlbnRzICkgew0KICAgIAkJCW1heCA9IG91dHN0YW5kaW5nRXZlbnRzOw0KICAgIAkJfQ0KICAg
IAl9DQogICAgCUlEYXRhVXRpbC5wdXQocGlwZWxpbmVDdXJzb3IsICJvdXRzdGFuZGluZ0V2ZW50
c1NoYXJlZER1cmFibGVNYXgiLCBtYXggKyAiIik7DQogICAgCUlEYXRhVXRpbC5wdXQocGlwZWxp
bmVDdXJzb3IsICJzaGFyZWREdXJhYmxlT3V0c3RhbmRpbmdFdmVudHMiLHNoYXJlZER1cmFibGVP
dXRzdGFuZGluZ0V2ZW50cyk7DQogICAgfSANCiAgICANCgkvLyBub24gc2hhcmQgZHVyYWJsZSwN
CiAgICAvLyBhcyB3ZWxsIGFzIElTIE5hdGl2ZSBNZXNzYWdpbmcgVHJpZ2dlciB3aXRoIFNlcmlh
bCBQcm9jZXNzaW5nIG9uIFNoYXJlZCBEdXJhYmxlIENvbm5lY3Rpb24gDQogICAgLyoNCiAgICAg
KiBJZiBhIHdNIG1lc3NhZ2luZyB0cmlnZ2VyIGhhcyBhIHNoYXJlZCBkdXJhYmxlIGNvbm5lY3Rp
b24sIGJ1dCBkb2VzIHNlcmlhbCBwcm9jZXNzaW5nLA0KICAgICAqIHRoZW4gdGhlIGV2ZW50IGlz
IHN0b3JlZCBkaXJlY3RseSBpbiB0aGUgY2hhbm5lbCwgdGhlcmVmb3JlIHdlIGNhbiBqdXN0IGdl
dCB0aGUgZXZlbnQgY291bnQNCiAgICAgKiBmb3IgdGhlIHRvcGljIA0KICAgICAqLw0KCUlEYXRh
VXRpbC5wdXQocGlwZWxpbmVDdXJzb3IsICJvdXRzdGFuZGluZ0V2ZW50cyIsIGNoYW5uZWwuZ2V0
RXZlbnRDb3VudCgpICsgIiIpOw0KICAgIA0KICAgIHBpcGVsaW5lQ3Vyc29yLmRlc3Ryb3koKTsN
CgkNCn0gY2F0Y2ggKEV4Y2VwdGlvbiBlKSB7DQoJLy8gVE9ETyBBdXRvLWdlbmVyYXRlZCBjYXRj
aCBibG9jaw0KCWUucHJpbnRTdGFja1RyYWNlKCk7DQoJdGhyb3cgbmV3IFNlcnZpY2VFeGNlcHRp
b24oZSk7DQp9DQoNCgkNCg==</value>
</Values>
