<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">writeStringToFile</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:0:required string</value>
    <value>[i] field:0:required filename</value>
    <value>[i] field:0:required append {"true","false"}</value>
    <value>[i] field:0:optional addNewLine</value>
    <value>[i] field:0:optional context</value>
    <value>[i] field:0:required dir</value>
    <value>[i] field:0:optional encoding</value>
  </array>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUKSURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRDdXJz
b3IoKTsKU3RyaW5nCXN0cmluZyA9IElEYXRhVXRpbC5nZXRTdHJpbmcoIHBpcGVsaW5lQ3Vyc29y
LCJzdHJpbmciICk7ClN0cmluZwlmaWxlbmFtZSA9IElEYXRhVXRpbC5nZXRTdHJpbmcoIHBpcGVs
aW5lQ3Vyc29yLCAiZmlsZW5hbWUiICk7ClN0cmluZwlhcHBlbmQgPSBJRGF0YVV0aWwuZ2V0U3Ry
aW5nKCBwaXBlbGluZUN1cnNvciwgImFwcGVuZCIgKTsKU3RyaW5nCWNvbnRleHQgPSBJRGF0YVV0
aWwuZ2V0U3RyaW5nKCBwaXBlbGluZUN1cnNvciwgImNvbnRleHQiICk7ClN0cmluZwlkaXIgPSBJ
RGF0YVV0aWwuZ2V0U3RyaW5nKCBwaXBlbGluZUN1cnNvciwgImRpciIgKTsKU3RyaW5nCWVuY29k
aW5nID0gSURhdGFVdGlsLmdldFN0cmluZyggcGlwZWxpbmVDdXJzb3IsICJlbmNvZGluZyIgKTsK
U3RyaW5nCWFkZE5ld0xpbmUgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKCBwaXBlbGluZUN1cnNvciwg
ImFkZE5ld0xpbmUiICk7CnBpcGVsaW5lQ3Vyc29yLmRlc3Ryb3koKTsKCmlmKCBzdHJpbmcgPT0g
bnVsbCApIHsKCXRocm93IG5ldyBTZXJ2aWNlRXhjZXB0aW9uKCJJbnB1dCBzdHJpbmcgbXVzdCBu
b3QgYmUgbnVsbCAoYnV0IGNhbiBiZSBlbXB0eSkiKTsKfQppZiggZmlsZW5hbWUgPT0gbnVsbCAp
IHsKCXRocm93IG5ldyBTZXJ2aWNlRXhjZXB0aW9uKCJGaWxlbmFtZSBtdXN0IGJlIHByb3ZpZGVk
LiIpOwp9CmlmKCBhcHBlbmQgPT0gbnVsbCApIHsKCWFwcGVuZCA9ICJ0cnVlIjsKfQppZiggIShh
cHBlbmQuZXF1YWxzKCJ0cnVlIikgfHwgYXBwZW5kLmVxdWFscygiZmFsc2UiKSkgKSB7CglhcHBl
bmQgPSAidHJ1ZSI7Cn0KaWYoIGNvbnRleHQgPT0gbnVsbCApIHsKCWNvbnRleHQgPSAiZGVmYXVs
dCI7Cn0KaWYoIGFkZE5ld0xpbmUgPT0gbnVsbCApIHsKCWFkZE5ld0xpbmUgPSAiZmFsc2UiOwp9
CmlmKCBkaXIgPT0gbnVsbCApIHsKCXRocm93IG5ldyBTZXJ2aWNlRXhjZXB0aW9uKCJEaXJlY3Rv
cnkgbXVzdCBiZSBwcm92aWRlZC4iKTsKfQoKRmlsZSBiYXNlRGlyID0gbmV3IEZpbGUoZGlyKTsK
aWYoIGJhc2VEaXIuZXhpc3RzKCkgJiYgIWJhc2VEaXIuaXNEaXJlY3RvcnkoKSApIHsKCXRocm93
IG5ldyBTZXJ2aWNlRXhjZXB0aW9uKCJQcm92aWRlIGEgdmFsaWQgZGlyZWN0b3J5IHdoaWNoIGV4
aXN0cy4iKTsKfSBlbHNlIGlmKCAhYmFzZURpci5leGlzdHMoKSApIHsKCWJhc2VEaXIubWtkaXIo
KTsKfQoKRmlsZSBjb250ZXh0RGlyID0gbmV3IEZpbGUoYmFzZURpciwgY29udGV4dCk7CmlmKCAh
Y29udGV4dERpci5leGlzdHMoKSApIHsKCWNvbnRleHREaXIubWtkaXJzKCk7Cn0KCkZpbGUgdGFy
Z2V0RmlsZSA9IG5ldyBGaWxlKGNvbnRleHREaXIsIGZpbGVuYW1lKTsKaWYoIHRhcmdldEZpbGUu
ZXhpc3RzKCkgJiYgYXBwZW5kLmVxdWFscygiZmFsc2UiKSApIHsKCXRhcmdldEZpbGUuZGVsZXRl
KCk7Cn0KLy8JCUJ1ZmZlcmVkV3JpdGVyIGJ3ID0gbnVsbDsKT3V0cHV0U3RyZWFtV3JpdGVyIG9z
dyA9IG51bGw7CnRyeSB7Cglib29sZWFuIGFwcGVuZEJvb2wgPSBhcHBlbmQuZXF1YWxzKCJ0cnVl
IikgPyB0cnVlIDogZmFsc2U7Cglib29sZWFuIGFkZE5ld0xpbmVCb29sID0gYWRkTmV3TGluZS5l
cXVhbHMoInRydWUiKSA/IHRydWUgOiBmYWxzZTsKLy8JCQlGaWxlV3JpdGVyIGZ3ID0gbmV3IEZp
bGVXcml0ZXIodGFyZ2V0RmlsZSwgYXBwZW5kQm9vbCk7Ci8vCQkJYncgPSBuZXcgQnVmZmVyZWRX
cml0ZXIoZncpOwovLwkJCWJ3LndyaXRlKHN0cmluZyk7CQkJCglGaWxlT3V0cHV0U3RyZWFtIGZv
cyA9IG5ldyBGaWxlT3V0cHV0U3RyZWFtKHRhcmdldEZpbGUsIGFwcGVuZEJvb2wpOwoJaWYoIGVu
Y29kaW5nID09IG51bGwgfHwgIiIuZXF1YWxzKGVuY29kaW5nKSApIHsKCQlvc3cgPSBuZXcgT3V0
cHV0U3RyZWFtV3JpdGVyKGZvcyk7CQoJfSBlbHNlIHsKCQlvc3cgPSBuZXcgT3V0cHV0U3RyZWFt
V3JpdGVyKGZvcywgQ2hhcnNldC5mb3JOYW1lKGVuY29kaW5nKS5uZXdFbmNvZGVyKCkpOwoJfQoJ
aWYoIGFkZE5ld0xpbmVCb29sICkgewoJCXN0cmluZyA9IHN0cmluZyArIFN5c3RlbS5nZXRQcm9w
ZXJ0eSgibGluZS5zZXBhcmF0b3IiKTsKCX0KCW9zdy53cml0ZShzdHJpbmcpOwp9IGNhdGNoIChJ
T0V4Y2VwdGlvbiBlKSB7CiAgICB0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbigiRXhjZXB0aW9u
IG9jY3VyZWQgd2hlbiB3cml0aW5nIHRvIGZpbGUgIiArIHRhcmdldEZpbGUgKyAiOiAiICsgZSk7
Cn0gZmluYWxseSB7Cgl0cnkgewoJCW9zdy5jbG9zZSgpOwoJfSBjYXRjaCAoSU9FeGNlcHRpb24g
ZSkgewoJCS8vIGlnbm9yZQoJfQp9CgoJCg==</value>
</Values>
