<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">loadConfigurationFile</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:0:required configFile</value>
    <value>[i] field:0:optional packageName</value>
  </array>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgcGlwZWxpbmVDID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7ClN0cmluZyBjb25m
aWdGaWxlID0gSURhdGFVdGlsLmdldFN0cmluZyhwaXBlbGluZUMsICJjb25maWdGaWxlIik7ClN0
cmluZyBwYWNrYWdlTmFtZSA9IElEYXRhVXRpbC5nZXRTdHJpbmcocGlwZWxpbmVDLCAicGFja2Fn
ZU5hbWUiKTsKRmlsZSBjRmlsZSA9IG51bGw7CgppZiggcGFja2FnZU5hbWUgIT0gbnVsbCAmJiAh
IiIuZXF1YWxzKHBhY2thZ2VOYW1lKSApIHsKCUZpbGUgY29uZmlnRGlyID0gU2VydmVyQVBJLmdl
dFBhY2thZ2VDb25maWdEaXIocGFja2FnZU5hbWUpOwoJaWYoICFjb25maWdEaXIuZXhpc3RzKCkg
KSB7CgkJbG9nZ2VyLmVycm9yKCJDb3VsZCBub3QgbG9hZCAnIiArIGNvbmZpZ0ZpbGUgKyAiJyBm
cm9tIGNvbmZpZyBkaXIgb2YgcGFja2FnZSAiICsgcGFja2FnZU5hbWUgKyAiJzogY29uZmlnIGRp
ciBkb2VzIG5vdCBleGlzdC4iKTsJCQkJCgkJcmV0dXJuOwoJfQoJY0ZpbGUgPSBuZXcgRmlsZShj
b25maWdEaXIsIGNvbmZpZ0ZpbGUpOwoJaWYoICFjRmlsZS5leGlzdHMoKSApIHsKCQlsb2dnZXIu
ZXJyb3IoIkNvdWxkIG5vdCBsb2FkICciICsgY29uZmlnRmlsZSArICInIGZyb20gY29uZmlnIGRp
ciBvZiBwYWNrYWdlICciICsgcGFja2FnZU5hbWUgKyAiJzogY29uZmlnIGZpbGUgZG9lcyBub3Qg
ZXhpc3QuIik7CQkJCQoJCXJldHVybjsKCX0KfSBlbHNlIHsKCWNGaWxlID0gbmV3IEZpbGUoY29u
ZmlnRmlsZSk7CglpZiAoIWNGaWxlLmV4aXN0cygpKSB7CgkJbG9nZ2VyLmVycm9yKCJDb3VsZCBu
b3QgbG9hZCAnIiArIGNvbmZpZ0ZpbGUgKyAiOiBjb25maWcgZmlsZSBkb2VzIG5vdCBleGlzdCBp
biBkaXJlY3RvcnkgIiArIG5ldyBGaWxlKCIuIikuZ2V0QWJzb2x1dGVQYXRoKCkpOwkJCQkKCQly
ZXR1cm47Cgl9Cn0KaWYoIGNGaWxlICE9IG51bGwgKSB7Cglsb2dnZXIuZGVidWcoIkxvYWRpbmcg
Y29uZmlndXJhdGlvbiBmaWxlICIgKyBjRmlsZS5nZXRBYnNvbHV0ZVBhdGgoKSk7CglhZGRBc3Nl
dENvbmZpZ3VyYXRpb24oY0ZpbGUpOwp9CQkJCg==</value>
</Values>
