<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">getFile</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:0:required filename</value>
    <value>[i] field:0:optional context</value>
    <value>[i] field:0:required dir</value>
    <value>[i] field:0:optional encoding</value>
    <value>[o] field:0:required stringOut</value>
  </array>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUKSURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRDdXJz
b3IoKTsKU3RyaW5nCWZpbGVuYW1lID0gSURhdGFVdGlsLmdldFN0cmluZyggcGlwZWxpbmVDdXJz
b3IsICJmaWxlbmFtZSIgKTsKU3RyaW5nCWNvbnRleHQgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKCBw
aXBlbGluZUN1cnNvciwgImNvbnRleHQiICk7ClN0cmluZwlkaXIgPSBJRGF0YVV0aWwuZ2V0U3Ry
aW5nKCBwaXBlbGluZUN1cnNvciwgImRpciIgKTsKU3RyaW5nCWVuY29kaW5nID0gSURhdGFVdGls
LmdldFN0cmluZyggcGlwZWxpbmVDdXJzb3IsICJlbmNvZGluZyIgKTsKcGlwZWxpbmVDdXJzb3Iu
ZGVzdHJveSgpOwoKaWYoIGZpbGVuYW1lID09IG51bGwgKSB7Cgl0aHJvdyBuZXcgU2VydmljZUV4
Y2VwdGlvbigiRmlsZW5hbWUgbXVzdCBiZSBwcm92aWRlZC4iKTsKfQppZiggY29udGV4dCA9PSBu
dWxsICkgewoJY29udGV4dCA9ICJkZWZhdWx0IjsKfQppZiggZGlyID09IG51bGwgKSB7Cgl0aHJv
dyBuZXcgU2VydmljZUV4Y2VwdGlvbigiRGlyZWN0b3J5IG11c3QgYmUgcHJvdmlkZWQuIik7Cn0K
CkZpbGUgYmFzZURpciA9IG5ldyBGaWxlKGRpcik7CmlmKCBiYXNlRGlyLmV4aXN0cygpICYmICFi
YXNlRGlyLmlzRGlyZWN0b3J5KCkgKSB7Cgl0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbigiUHJv
dmlkZSBhIHZhbGlkIGRpcmVjdG9yeSB3aGljaCBleGlzdHMuIik7Cn0gZWxzZSBpZiggIWJhc2VE
aXIuZXhpc3RzKCkgKSB7CgliYXNlRGlyLm1rZGlyKCk7Cn0KCkZpbGUgY29udGV4dERpciA9IG5l
dyBGaWxlKGJhc2VEaXIsIGNvbnRleHQpOwppZiggIWNvbnRleHREaXIuZXhpc3RzKCkgKSB7Cglj
b250ZXh0RGlyLm1rZGlyKCk7Cn0KCkZpbGUgdGFyZ2V0RmlsZSA9IG5ldyBGaWxlKGNvbnRleHRE
aXIsIGZpbGVuYW1lKTsKaWYoICF0YXJnZXRGaWxlLmV4aXN0cygpICkgewoJcmV0dXJuOwp9CgpT
dHJpbmdCdWZmZXIgZmlsZURhdGEgPSBuZXcgU3RyaW5nQnVmZmVyKCk7CkJ1ZmZlcmVkUmVhZGVy
IHJlYWRlciA9IG51bGw7CnRyeSB7CglpZiggZW5jb2RpbmcgIT0gbnVsbCApIHsKCQlyZWFkZXIg
PSBuZXcgQnVmZmVyZWRSZWFkZXIobmV3IElucHV0U3RyZWFtUmVhZGVyKG5ldyBGaWxlSW5wdXRT
dHJlYW0odGFyZ2V0RmlsZSksIGVuY29kaW5nKSk7Cgl9IGVsc2UgewoJCXJlYWRlciA9IG5ldyBC
dWZmZXJlZFJlYWRlcihuZXcgRmlsZVJlYWRlcih0YXJnZXRGaWxlKSk7Cgl9CgljaGFyW10gYnVm
ID0gbmV3IGNoYXJbMTAyNF07CglpbnQgbnVtUmVhZD0wOwoJd2hpbGUoKG51bVJlYWQ9cmVhZGVy
LnJlYWQoYnVmKSkgIT0gLTEpewoJCVN0cmluZyByZWFkRGF0YSA9IFN0cmluZy52YWx1ZU9mKGJ1
ZiwgMCwgbnVtUmVhZCk7CgkJZmlsZURhdGEuYXBwZW5kKHJlYWREYXRhKTsKCX0KfSBjYXRjaCgg
RmlsZU5vdEZvdW5kRXhjZXB0aW9uIGZuZmUgKSB7Cgl0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlv
bigiRXhjZXB0aW9uIHdoZW4gcmVhZGluZyBmaWxlICIgKyB0YXJnZXRGaWxlICsgIjogIiArIGZu
ZmUpOwp9IGNhdGNoKCBJT0V4Y2VwdGlvbiBpb2UgKSAgewoJdGhyb3cgbmV3IFNlcnZpY2VFeGNl
cHRpb24oIkV4Y2VwdGlvbiB3aGVuIHJlYWRpbmcgZmlsZSAiICsgdGFyZ2V0RmlsZSArICI6ICIg
KyBpb2UpOwp9IGZpbmFsbHkgewoJdHJ5IHsKCXJlYWRlci5jbG9zZSgpOwoJfSBjYXRjaCggSU9F
eGNlcHRpb24gZSApIHsKCQkvLyBpZ25vcmUKCX0KfQpTdHJpbmcgc3RyaW5nT3V0ID0gZmlsZURh
dGEudG9TdHJpbmcoKTsKSURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3JfMSA9IHBpcGVsaW5lLmdl
dEN1cnNvcigpOwpJRGF0YVV0aWwucHV0KCBwaXBlbGluZUN1cnNvcl8xLCAic3RyaW5nT3V0Iiwg
c3RyaW5nT3V0ICk7CnBpcGVsaW5lQ3Vyc29yXzEuZGVzdHJveSgpOwoJCg==</value>
</Values>
