<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">getQueuedElementsJms</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:0:required RNAME</value>
    <value>[i] field:0:required jmsQueueName</value>
    <value>[o] field:0:required outstandingEvents</value>
  </array>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">dHJ5IHsKCQoJLy8gcGlwZWxpbmUKCUlEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yID0gcGlwZWxp
bmUuZ2V0Q3Vyc29yKCk7CglTdHJpbmcJUk5BTUUgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKCBwaXBl
bGluZUN1cnNvciwgIlJOQU1FIiApOwoJU3RyaW5nCWptc1F1ZXVlTmFtZSA9IElEYXRhVXRpbC5n
ZXRTdHJpbmcoIHBpcGVsaW5lQ3Vyc29yLCAiam1zUXVldWVOYW1lIiApOwoJCglpZiggUk5BTUUg
PT0gbnVsbCB8fCAiIi5lcXVhbHMoUk5BTUUpICkgIHsKCQl0aHJvdyBuZXcgU2VydmljZUV4Y2Vw
dGlvbigiUk5BTUUgbXVzdCBub3QgYmUgZW1wdHkuIFByb3ZpZGUgbGlrZTogJ25zcDovL2hvc3Q6
cG9ydCcuIik7Cgl9CglpZiggam1zUXVldWVOYW1lID09IG51bGwgfHwgIiIuZXF1YWxzKGptc1F1
ZXVlTmFtZSkgKSB7CgkJdGhyb3cgbmV3IFNlcnZpY2VFeGNlcHRpb24oImptc1F1ZXVlTmFtZSBt
dXN0IG5vdCBiZSBudWxsLiIpOwoJfQoJCgluU2Vzc2lvbkF0dHJpYnV0ZXMgbnNhPW5ldyBuU2Vz
c2lvbkF0dHJpYnV0ZXMoUk5BTUUpOwoJblNlc3Npb24gbXlTZXNzaW9uID0gblNlc3Npb25GYWN0
b3J5LmNyZWF0ZShuc2EpOwoJbXlTZXNzaW9uLmluaXQoKTsKCgluQ2hhbm5lbEF0dHJpYnV0ZXMg
YXR0cmliID0gbmV3IG5DaGFubmVsQXR0cmlidXRlcygpOwogICAgYXR0cmliLnNldE5hbWUoam1z
UXVldWVOYW1lKTsKICAgIGNvbS5wY2JzeXMubmlydmFuYS5jbGllbnQubkZpbmRSZXN1bHRbXSBm
aW5kUmVzdWx0ID0gbXlTZXNzaW9uLmZpbmQobmV3IG5DaGFubmVsQXR0cmlidXRlc1tdIHthdHRy
aWJ9KTsKICAgIGlmKCBmaW5kUmVzdWx0Lmxlbmd0aCA9PSAwICkgewogICAgCXRocm93IG5ldyBT
ZXJ2aWNlRXhjZXB0aW9uKCJKTVMgcXVldWUgIiArIGptc1F1ZXVlTmFtZSArICIgd2FzIG5vdCBm
b3VuZCBvbiByZWFsbSAiICsgUk5BTUUpOwogICAgfQogICAgaWYoIGZpbmRSZXN1bHRbMF0uaXND
aGFubmVsKCkgKSB7CiAgICAJLy8gaWYgaXQgaXMgYSBjaGFubmVsLCB0aGVuIGl0IGlzIGEgam1z
IHRvcGljCiAgICAJSURhdGFVdGlsLnB1dCggcGlwZWxpbmVDdXJzb3IsICJ0b3BpY05hbWUiLCBq
bXNRdWV1ZU5hbWUgKTsKICAgIAlnZXRRdWV1ZWRFbGVtZW50c0ptc1RvcGljKHBpcGVsaW5lKTsK
ICAgIH0gZWxzZSBpZiggZmluZFJlc3VsdFswXS5pc1F1ZXVlKCkgKSB7CiAgICAJLy8gdGhpcyBp
cyBhIGptcyBxdWV1ZQogICAgCUlEYXRhVXRpbC5wdXQoIHBpcGVsaW5lQ3Vyc29yLCAicXVldWVO
YW1lIiwgam1zUXVldWVOYW1lICk7CiAgICAJZ2V0UXVldWVkRWxlbWVudHNKbXNRdWV1ZShwaXBl
bGluZSk7CiAgICB9IGVsc2UgewogICAgCXRocm93IG5ldyBTZXJ2aWNlRXhjZXB0aW9uKCJKTVMg
cXVldWUgIiArIGptc1F1ZXVlTmFtZSArICIgb24gcmVhbG0gIiArIFJOQU1FICsgIiBpcyBuZWl0
aGVyIHF1ZXVlIG5vciBjaGFubmVsLiIpOwogICAgfQogICAgcGlwZWxpbmVDdXJzb3IuZGVzdHJv
eSgpOwp9IGNhdGNoIChFeGNlcHRpb24gZSkgewoJLy8gVE9ETyBBdXRvLWdlbmVyYXRlZCBjYXRj
aCBibG9jawoJZS5wcmludFN0YWNrVHJhY2UoKTsKCXRocm93IG5ldyBTZXJ2aWNlRXhjZXB0aW9u
KGUpOwp9Cg==</value>
</Values>
