<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">getQueuedElementsJmsTopic</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:0:required RNAME</value>
    <value>[i] field:0:required topicName</value>
    <value>[o] field:0:required outstandingEvents</value>
    <value>[o] field:0:required queueStorageSize</value>
  </array>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">dHJ5IHsKCQoJLy8gcGlwZWxpbmUKCUlEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yID0gcGlwZWxp
bmUuZ2V0Q3Vyc29yKCk7CglTdHJpbmcJUk5BTUUgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKCBwaXBl
bGluZUN1cnNvciwgIlJOQU1FIiApOwoJU3RyaW5nCXRvcGljTmFtZSA9IElEYXRhVXRpbC5nZXRT
dHJpbmcoIHBpcGVsaW5lQ3Vyc29yLCAidG9waWNOYW1lIiApOwoJCglpZiggUk5BTUUgPT0gbnVs
bCB8fCAiIi5lcXVhbHMoUk5BTUUpICkgIHsKCQl0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbigi
Uk5BTUUgbXVzdCBub3QgYmUgZW1wdHkuIFByb3ZpZGUgbGlrZTogJ25zcDovL2hvc3Q6cG9ydCcu
Iik7Cgl9CglpZiggdG9waWNOYW1lID09IG51bGwgfHwgIiIuZXF1YWxzKHRvcGljTmFtZSkgKSB7
CgkJdGhyb3cgbmV3IFNlcnZpY2VFeGNlcHRpb24oInRvcGljTmFtZSBtdXN0IG5vdCBiZSBudWxs
LiIpOwoJfQoJCgluU2Vzc2lvbkF0dHJpYnV0ZXMgbnNhPW5ldyBuU2Vzc2lvbkF0dHJpYnV0ZXMo
Uk5BTUUpOwoJblNlc3Npb24gICAgICBteVNlc3Npb24gPSBuU2Vzc2lvbkZhY3RvcnkuY3JlYXRl
KG5zYSk7CglteVNlc3Npb24uaW5pdCgpOwoKCW5DaGFubmVsQXR0cmlidXRlcyBhdHRyaWIgPSBu
ZXcgbkNoYW5uZWxBdHRyaWJ1dGVzKCk7CiAgICBhdHRyaWIuc2V0TmFtZSh0b3BpY05hbWUpOwog
ICAgbkNoYW5uZWwgY2hhbm5lbCA9IG15U2Vzc2lvbi5maW5kQ2hhbm5lbChhdHRyaWIpOwoKICAg
IG5SZWFsbU5vZGUgcmVhbG1Ob2RlID0gbmV3IG5SZWFsbU5vZGUobnNhKTsKICAgIG5Ob2RlIG5v
ZGUgPSByZWFsbU5vZGUuZmluZE5vZGUodG9waWNOYW1lKTsKICAgIGlmIChub2RlIGluc3RhbmNl
b2YgbkxlYWZOb2RlKSB7CgkJaWYgKCgobkxlYWZOb2RlKSBub2RlKS5pc0NoYW5uZWwoKSB8fCAo
KG5MZWFmTm9kZSkgbm9kZSkuaXNRdWV1ZSgpKSB7CgkJCW5MZWFmTm9kZSBsZWFmTm9kZSA9IChu
TGVhZk5vZGUpbm9kZTsKCQkJSURhdGFVdGlsLnB1dChwaXBlbGluZUN1cnNvciwgInF1ZXVlU3Rv
cmFnZVNpemUiLCBsZWFmTm9kZS5nZXRVc2VkU3BhY2UoKSArICIiKTsKLy8JCQkJCUlEYXRhVXRp
bC5wdXQocGlwZWxpbmVDdXJzb3IsICJnZXRDdXJyZW50TnVtYmVyT2ZFdmVudHMiLCBsZWFmTm9k
ZS5nZXRDdXJyZW50TnVtYmVyT2ZFdmVudHMoKSArICIiKTsKCQl9Cgl9CiAgICBJRGF0YVV0aWwu
cHV0KHBpcGVsaW5lQ3Vyc29yLCAib3V0c3RhbmRpbmdFdmVudHMiLCBjaGFubmVsLmdldEV2ZW50
Q291bnQoKSArICIiKTsKICAgIHBpcGVsaW5lQ3Vyc29yLmRlc3Ryb3koKTsKCQp9IGNhdGNoIChF
eGNlcHRpb24gZSkgewoJLy8gVE9ETyBBdXRvLWdlbmVyYXRlZCBjYXRjaCBibG9jawoJZS5wcmlu
dFN0YWNrVHJhY2UoKTsKCXRocm93IG5ldyBTZXJ2aWNlRXhjZXB0aW9uKGUpOwp9CgoJCg==</value>
</Values>
