<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">getQueuedElementsJmsTopic</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:0:required RNAME</value>
    <value>[i] field:0:required topicName</value>
    <value>[o] field:0:required outstandingEvents</value>
    <value>[o] field:0:required queueStorageSize</value>
  </array>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">dHJ5IHsNCgkNCgkvLyBwaXBlbGluZQ0KCUlEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yID0gcGlw
ZWxpbmUuZ2V0Q3Vyc29yKCk7DQoJU3RyaW5nCVJOQU1FID0gSURhdGFVdGlsLmdldFN0cmluZygg
cGlwZWxpbmVDdXJzb3IsICJSTkFNRSIgKTsNCglTdHJpbmcJdG9waWNOYW1lID0gSURhdGFVdGls
LmdldFN0cmluZyggcGlwZWxpbmVDdXJzb3IsICJ0b3BpY05hbWUiICk7DQoJDQoJaWYoIFJOQU1F
ID09IG51bGwgfHwgIiIuZXF1YWxzKFJOQU1FKSApICB7DQoJCXRocm93IG5ldyBTZXJ2aWNlRXhj
ZXB0aW9uKCJSTkFNRSBtdXN0IG5vdCBiZSBlbXB0eS4gUHJvdmlkZSBsaWtlOiAnbnNwOi8vaG9z
dDpwb3J0Jy4iKTsNCgl9DQoJaWYoIHRvcGljTmFtZSA9PSBudWxsIHx8ICIiLmVxdWFscyh0b3Bp
Y05hbWUpICkgew0KCQl0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbigidG9waWNOYW1lIG11c3Qg
bm90IGJlIG51bGwuIik7DQoJfQ0KCQ0KCW5TZXNzaW9uQXR0cmlidXRlcyBuc2E9bmV3IG5TZXNz
aW9uQXR0cmlidXRlcyhSTkFNRSk7DQoJblNlc3Npb24gICAgICBteVNlc3Npb24gPSBuU2Vzc2lv
bkZhY3RvcnkuY3JlYXRlKG5zYSk7DQoJbXlTZXNzaW9uLmluaXQoKTsNCg0KCW5DaGFubmVsQXR0
cmlidXRlcyBhdHRyaWIgPSBuZXcgbkNoYW5uZWxBdHRyaWJ1dGVzKCk7DQogICAgYXR0cmliLnNl
dE5hbWUodG9waWNOYW1lKTsNCiAgICBuQ2hhbm5lbCBjaGFubmVsID0gbXlTZXNzaW9uLmZpbmRD
aGFubmVsKGF0dHJpYik7DQoNCiAgICBuUmVhbG1Ob2RlIHJlYWxtTm9kZSA9IG5ldyBuUmVhbG1O
b2RlKG5zYSk7DQogICAgbk5vZGUgbm9kZSA9IHJlYWxtTm9kZS5maW5kTm9kZSh0b3BpY05hbWUp
Ow0KICAgIGlmIChub2RlIGluc3RhbmNlb2YgbkxlYWZOb2RlKSB7DQoJCWlmICgoKG5MZWFmTm9k
ZSkgbm9kZSkuaXNDaGFubmVsKCkgfHwgKChuTGVhZk5vZGUpIG5vZGUpLmlzUXVldWUoKSkgew0K
CQkJbkxlYWZOb2RlIGxlYWZOb2RlID0gKG5MZWFmTm9kZSlub2RlOw0KCQkJSURhdGFVdGlsLnB1
dChwaXBlbGluZUN1cnNvciwgInF1ZXVlU3RvcmFnZVNpemUiLCBsZWFmTm9kZS5nZXRVc2VkU3Bh
Y2UoKSArICIiKTsNCi8vCQkJCQlJRGF0YVV0aWwucHV0KHBpcGVsaW5lQ3Vyc29yLCAiZ2V0Q3Vy
cmVudE51bWJlck9mRXZlbnRzIiwgbGVhZk5vZGUuZ2V0Q3VycmVudE51bWJlck9mRXZlbnRzKCkg
KyAiIik7DQoJCX0NCgl9DQogICAgSURhdGFVdGlsLnB1dChwaXBlbGluZUN1cnNvciwgIm91dHN0
YW5kaW5nRXZlbnRzIiwgY2hhbm5lbC5nZXRFdmVudENvdW50KCkgKyAiIik7DQogICAgcGlwZWxp
bmVDdXJzb3IuZGVzdHJveSgpOw0KCQ0KfSBjYXRjaCAoRXhjZXB0aW9uIGUpIHsNCgkvLyBUT0RP
IEF1dG8tZ2VuZXJhdGVkIGNhdGNoIGJsb2NrDQoJZS5wcmludFN0YWNrVHJhY2UoKTsNCgl0aHJv
dyBuZXcgU2VydmljZUV4Y2VwdGlvbihlKTsNCn0NCg0KCQ0K</value>
</Values>
