<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">getIntervalForInterface</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgcGlwZWxpbmVDID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQpTdHJpbmcgaW50
ZXJmYWNlTmFtZSA9IElEYXRhVXRpbC5nZXRTdHJpbmcocGlwZWxpbmVDLCAiaW50ZXJmYWNlIik7
DQppZiggaW50ZXJmYWNlTmFtZSA9PSBudWxsIHx8ICIiLmVxdWFscyhpbnRlcmZhY2VOYW1lKSAp
IHsNCgl0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbigiUHJvdmlkZSBhbiBpbnRlcmZhY2UgdG8g
bG9va3VwIHRoZSBpbnRlcnZhbCBmb3IuIik7DQp9DQppZiggaW50ZXJmYWNlcyA9PSBudWxsICkg
ew0KCWNhbGxQYXJzZUNvbmZpZygpOw0KCWlmKCBpbnRlcmZhY2VzID09IG51bGwgKSB7DQoJCXRo
cm93IG5ldyBTZXJ2aWNlRXhjZXB0aW9uKCJDb25maWcgY2Fubm90IGJlIHJlYWQuIFVzZSB3eC5w
bGF0Zm9ybU1vbml0b3JpbmcuaW1wbC5jb25maWc6cGFyc2VDb25maWciKTsNCgl9DQp9DQpmb3Ig
KEpzb25WYWx1ZSBpIDogaW50ZXJmYWNlcykgew0KICBTdHJpbmcgbmFtZSA9IGkuYXNPYmplY3Qo
KS5nZXQoImludGVyZmFjZSIpLmFzU3RyaW5nKCk7DQogIGlmKCBuYW1lLmVxdWFscyhpbnRlcmZh
Y2VOYW1lKSApIHsNCgkgIElEYXRhVXRpbC5wdXQocGlwZWxpbmVDLCAiaW50ZXJ2YWwiLCBpLmFz
T2JqZWN0KCkuZ2V0KCJpbnRlcnZhbCIpLmFzU3RyaW5nKCkpOw0KCSAgcGlwZWxpbmVDLmRlc3Ry
b3koKTsNCgkgIHJldHVybjsNCiAgfQ0KfQ0KcGlwZWxpbmVDLmRlc3Ryb3koKTsNCi8vCQl0aHJv
dyBuZXcgU2VydmljZUV4Y2VwdGlvbigiTm8gaW50ZXJmYWNlIHdpdGggbmFtZSAiICsgaW50ZXJm
YWNlTmFtZSArICIgZGVmaW5lZCBpbiBjb25maWd1cmF0aW9uISIpOw==</value>
</Values>
