<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">getRNAMEByMessagingConnectionAlias</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:0:required useDefaultMessagingConnectionAlias {"true","false"}</value>
    <value>[i] field:0:required messagingConnectionAlias</value>
    <value>[o] field:0:required RNAME</value>
  </array>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUKSURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRDdXJz
b3IoKTsKU3RyaW5nCXVzZURlZmF1bHRNZXNzYWdpbmdDb25uZWN0aW9uQWxpYXMgPSBJRGF0YVV0
aWwuZ2V0U3RyaW5nKCBwaXBlbGluZUN1cnNvciwgInVzZURlZmF1bHRNZXNzYWdpbmdDb25uZWN0
aW9uQWxpYXMiICk7ClN0cmluZwltZXNzYWdpbmdDb25uZWN0aW9uQWxpYXMgPSBJRGF0YVV0aWwu
Z2V0U3RyaW5nKCBwaXBlbGluZUN1cnNvciwgIm1lc3NhZ2luZ0Nvbm5lY3Rpb25BbGlhcyIgKTsK
CmlmKCB1c2VEZWZhdWx0TWVzc2FnaW5nQ29ubmVjdGlvbkFsaWFzID09IG51bGwgfHwgIiIuZXF1
YWxzKHVzZURlZmF1bHRNZXNzYWdpbmdDb25uZWN0aW9uQWxpYXMpICkgewoJdXNlRGVmYXVsdE1l
c3NhZ2luZ0Nvbm5lY3Rpb25BbGlhcyA9ICJmYWxzZSI7Cn0KaWYoKCBtZXNzYWdpbmdDb25uZWN0
aW9uQWxpYXMgPT0gbnVsbCB8fCAiIi5lcXVhbHMobWVzc2FnaW5nQ29ubmVjdGlvbkFsaWFzKSAp
ICYmIHVzZURlZmF1bHRNZXNzYWdpbmdDb25uZWN0aW9uQWxpYXMuZXF1YWxzKCJmYWxzZSIpKSB7
Cgl0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbigiRWl0aGVyIHByb3ZpZGUgYSBtZXNzYWdpbmdD
b25uZWN0aW9uQWxpYXMsIG9yIHNldCB1c2VEZWZhdWx0TWVzc2FnaW5nQ29ubmVjdGlvbkFsaWFz
PXRydWUiKTsKfQoKSURhdGEgCW91dHB1dCA9IElEYXRhRmFjdG9yeS5jcmVhdGUoKTsKdHJ5ewoJ
b3V0cHV0ID0gU2VydmljZS5kb0ludm9rZSggIndtLnNlcnZlci5tZXNzYWdpbmciLCAiZ2V0Q29u
bmVjdGlvbkFsaWFzUmVwb3J0IiwgSURhdGFGYWN0b3J5LmNyZWF0ZSgpICk7Cn1jYXRjaCggRXhj
ZXB0aW9uIGUpewoJdGhyb3cgbmV3IFNlcnZpY2VFeGNlcHRpb24oIkNvdWxkIG5vdCBpbnZva2Ug
d20uc2VydmVyLm1lc3NhZ2luZzpnZXRDb25uZWN0aW9uQWxpYXNSZXBvcnQ6ICIgKyBlKTsKfQoK
SURhdGFbXSBhbGlhc0RhdGFMaXN0ID0gSURhdGFVdGlsLmdldElEYXRhQXJyYXkob3V0cHV0Lmdl
dEN1cnNvcigpLCAiYWxpYXNEYXRhTGlzdCIpOwpTdHJpbmcgdW1fcm5hbWUgPSBudWxsOwpmb3Io
IElEYXRhIGFsaWFzRGF0YSA6IGFsaWFzRGF0YUxpc3QgKSB7Ci8vCQkJYWxpYXNEYXRhTGlzdC9h
bGlhc0RhdGFMaXN0WzBdL2RlZmF1bHRBbGlhcwoJSURhdGFDdXJzb3IgYWxpYXNEYXRhQyA9IGFs
aWFzRGF0YS5nZXRDdXJzb3IoKTsKCWJvb2xlYW4gaXNEZWZhdWx0QWxpYXMgPSBJRGF0YVV0aWwu
Z2V0Qm9vbGVhbihhbGlhc0RhdGFDLCAiZGVmYXVsdEFsaWFzIik7CglTdHJpbmcgYWxpYXNOYW1l
ID0gSURhdGFVdGlsLmdldFN0cmluZyhhbGlhc0RhdGFDLCAiYWxpYXNOYW1lIik7CglpZiggdXNl
RGVmYXVsdE1lc3NhZ2luZ0Nvbm5lY3Rpb25BbGlhcy5lcXVhbHMoInRydWUiKSAmJiBpc0RlZmF1
bHRBbGlhcyApIHsKCQl1bV9ybmFtZSA9IElEYXRhVXRpbC5nZXRTdHJpbmcoYWxpYXNEYXRhQywg
InVtX3JuYW1lIik7CgkJYnJlYWs7Cgl9IGVsc2UgaWYoYWxpYXNOYW1lLmVxdWFscyhtZXNzYWdp
bmdDb25uZWN0aW9uQWxpYXMpICkgewoJCXVtX3JuYW1lID0gSURhdGFVdGlsLmdldFN0cmluZyhh
bGlhc0RhdGFDLCAidW1fcm5hbWUiKTsKCQlicmVhazsKCX0KfQppZiAoIHVtX3JuYW1lID09IG51
bGwgKSB7Cgl0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbigiRGlkIG5vdCBmaW5kIGFuIG1lc3Nh
Z2luZyBjb25uZWN0aW9uIGFsaWFzLiBQYXJhbWV0ZXJzOiB1c2VEZWZhdWx0TWVzc2FnaW5nQ29u
bmVjdGlvbkFsaWFzPSciICArIHVzZURlZmF1bHRNZXNzYWdpbmdDb25uZWN0aW9uQWxpYXMgKyAi
JywgbWVzc2FnaW5nQ29ubmVjdGlvbkFsaWFzPSciICsgbWVzc2FnaW5nQ29ubmVjdGlvbkFsaWFz
ICsgIicuIik7Cn0KCklEYXRhVXRpbC5wdXQoIHBpcGVsaW5lQ3Vyc29yLCAiUk5BTUUiLCB1bV9y
bmFtZSApOwpwaXBlbGluZUN1cnNvci5kZXN0cm95KCk7Cg==</value>
</Values>
