<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">stringToFile</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:0:required fileName</value>
    <value>[i] field:0:required data</value>
    <value>[i] field:0:optional append {"false","true"}</value>
    <value>[i] field:0:optional encoding</value>
  </array>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUKSURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRDdXJz
b3IoKTsKU3RyaW5nCWZpbGVOYW1lID0gSURhdGFVdGlsLmdldFN0cmluZyggcGlwZWxpbmVDdXJz
b3IsICJmaWxlTmFtZSIgKTsKU3RyaW5nCWRhdGEgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKCBwaXBl
bGluZUN1cnNvciwgImRhdGEiICk7ClN0cmluZwlhcHBlbmQgPSBJRGF0YVV0aWwuZ2V0U3RyaW5n
KCBwaXBlbGluZUN1cnNvciwgImFwcGVuZCIgKTsKU3RyaW5nCWVuY29kaW5nID0gSURhdGFVdGls
LmdldFN0cmluZyggcGlwZWxpbmVDdXJzb3IsICJlbmNvZGluZyIgKTsKcGlwZWxpbmVDdXJzb3Iu
ZGVzdHJveSgpOwoKaWYoIGZpbGVOYW1lID09IG51bGwgfHwgZmlsZU5hbWUuZXF1YWxzKCIiKSAp
IHsKCXRocm93IG5ldyBTZXJ2aWNlRXhjZXB0aW9uKCJXeFV0aWxpdGllcy5zdHJpbmdUb0ZpbGU6
IGZpbGVOYW1lIG11c3Qgbm90IGJlIGVtcHR5LiIpOwp9CmlmKCBhcHBlbmQgPT0gbnVsbCApIHsK
CWFwcGVuZCA9ICJmYWxzZSI7IAp9CmlmKCAhKGFwcGVuZC5lcXVhbHNJZ25vcmVDYXNlKCJ0cnVl
IikgfHwgYXBwZW5kLmVxdWFsc0lnbm9yZUNhc2UoImZhbHNlIikgKSApIHsKCXRocm93IG5ldyBT
ZXJ2aWNlRXhjZXB0aW9uKCJXeFV0aWxpdGllcy5zdHJpbmdUb0ZpbGU6IGFwcGVuZCBtdXN0IGVp
dGhlciBiZSAndHJ1ZScgb3IgJ2ZhbHNlJy4gSWYgbm90IHNldCwgZGVmYXVsdCBpcyAnZmFsc2Un
LiIpOwp9CmJvb2xlYW4gYm9vbEFwcGVuZCA9IGZhbHNlOwppZiggYXBwZW5kLmVxdWFsc0lnbm9y
ZUNhc2UoInRydWUiKSApIHsKCWJvb2xBcHBlbmQgPSB0cnVlOwp9ClByaW50V3JpdGVyIG91dCA9
IG51bGw7IAp0cnkgewogICAgRmlsZSBmaWxlID0gbmV3IEZpbGUoZmlsZU5hbWUpOwogICAgRmls
ZU91dHB1dFN0cmVhbSBmb3MgPSBuZXcgRmlsZU91dHB1dFN0cmVhbShmaWxlLCBib29sQXBwZW5k
ICk7CiAgICBPdXRwdXRTdHJlYW1Xcml0ZXIgb3N3ID0gbnVsbDsKICAgIGlmKCBlbmNvZGluZyAh
PSBudWxsICkgewogICAgCW9zdyA9IG5ldyBPdXRwdXRTdHJlYW1Xcml0ZXIoZm9zLCBlbmNvZGlu
Zyk7CiAgICB9IGVsc2UgewoJICAgIG9zdyA9IG5ldyBPdXRwdXRTdHJlYW1Xcml0ZXIoZm9zKTsK
ICAgIH0KICAgIG91dCA9IG5ldyBQcmludFdyaXRlcihvc3cpOwogICAgb3V0LnByaW50KGRhdGEp
Owp9IGNhdGNoIChJT0V4Y2VwdGlvbiBlKSB7CiAgICB0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlv
bigiV3hVdGlsaXRpZXMuc3RyaW5nVG9GaWxlOiBhbiBleGNlcHRpb24gb2NjdXJlZCB3aGVuIHRy
eWluZyB0byB3cml0ZSB0byBmaWxlICciICsgZmlsZU5hbWUgKyAiJzogIiArIGUpOwp9IGZpbmFs
bHkgewoJaWYoIG91dCAhPSBudWxsICkgewoJCW91dC5jbG9zZSgpOwoJfQp9Cg==</value>
</Values>
