<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">writeStringToFile</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:0:required string</value>
    <value>[i] field:0:required filename</value>
    <value>[i] field:0:required append {"true","false"}</value>
    <value>[i] field:0:optional addNewLine</value>
    <value>[i] field:0:optional context</value>
    <value>[i] field:0:required dir</value>
    <value>[i] field:0:optional encoding</value>
  </array>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUNCklEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vy
c29yKCk7DQpTdHJpbmcJc3RyaW5nID0gSURhdGFVdGlsLmdldFN0cmluZyggcGlwZWxpbmVDdXJz
b3IsInN0cmluZyIgKTsNClN0cmluZwlmaWxlbmFtZSA9IElEYXRhVXRpbC5nZXRTdHJpbmcoIHBp
cGVsaW5lQ3Vyc29yLCAiZmlsZW5hbWUiICk7DQpTdHJpbmcJYXBwZW5kID0gSURhdGFVdGlsLmdl
dFN0cmluZyggcGlwZWxpbmVDdXJzb3IsICJhcHBlbmQiICk7DQpTdHJpbmcJY29udGV4dCA9IElE
YXRhVXRpbC5nZXRTdHJpbmcoIHBpcGVsaW5lQ3Vyc29yLCAiY29udGV4dCIgKTsNClN0cmluZwlk
aXIgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKCBwaXBlbGluZUN1cnNvciwgImRpciIgKTsNClN0cmlu
ZwllbmNvZGluZyA9IElEYXRhVXRpbC5nZXRTdHJpbmcoIHBpcGVsaW5lQ3Vyc29yLCAiZW5jb2Rp
bmciICk7DQpTdHJpbmcJYWRkTmV3TGluZSA9IElEYXRhVXRpbC5nZXRTdHJpbmcoIHBpcGVsaW5l
Q3Vyc29yLCAiYWRkTmV3TGluZSIgKTsNCnBpcGVsaW5lQ3Vyc29yLmRlc3Ryb3koKTsNCg0KaWYo
IHN0cmluZyA9PSBudWxsICkgew0KCXRocm93IG5ldyBTZXJ2aWNlRXhjZXB0aW9uKCJJbnB1dCBz
dHJpbmcgbXVzdCBub3QgYmUgbnVsbCAoYnV0IGNhbiBiZSBlbXB0eSkiKTsNCn0NCmlmKCBmaWxl
bmFtZSA9PSBudWxsICkgew0KCXRocm93IG5ldyBTZXJ2aWNlRXhjZXB0aW9uKCJGaWxlbmFtZSBt
dXN0IGJlIHByb3ZpZGVkLiIpOw0KfQ0KaWYoIGFwcGVuZCA9PSBudWxsICkgew0KCWFwcGVuZCA9
ICJ0cnVlIjsNCn0NCmlmKCAhKGFwcGVuZC5lcXVhbHMoInRydWUiKSB8fCBhcHBlbmQuZXF1YWxz
KCJmYWxzZSIpKSApIHsNCglhcHBlbmQgPSAidHJ1ZSI7DQp9DQppZiggY29udGV4dCA9PSBudWxs
ICkgew0KCWNvbnRleHQgPSAiZGVmYXVsdCI7DQp9DQppZiggYWRkTmV3TGluZSA9PSBudWxsICkg
ew0KCWFkZE5ld0xpbmUgPSAiZmFsc2UiOw0KfQ0KaWYoIGRpciA9PSBudWxsICkgew0KCXRocm93
IG5ldyBTZXJ2aWNlRXhjZXB0aW9uKCJEaXJlY3RvcnkgbXVzdCBiZSBwcm92aWRlZC4iKTsNCn0N
Cg0KRmlsZSBiYXNlRGlyID0gbmV3IEZpbGUoZGlyKTsNCmlmKCBiYXNlRGlyLmV4aXN0cygpICYm
ICFiYXNlRGlyLmlzRGlyZWN0b3J5KCkgKSB7DQoJdGhyb3cgbmV3IFNlcnZpY2VFeGNlcHRpb24o
IlByb3ZpZGUgYSB2YWxpZCBkaXJlY3Rvcnkgd2hpY2ggZXhpc3RzLiIpOw0KfSBlbHNlIGlmKCAh
YmFzZURpci5leGlzdHMoKSApIHsNCgliYXNlRGlyLm1rZGlyKCk7DQp9DQoNCkZpbGUgY29udGV4
dERpciA9IG5ldyBGaWxlKGJhc2VEaXIsIGNvbnRleHQpOw0KaWYoICFjb250ZXh0RGlyLmV4aXN0
cygpICkgew0KCWNvbnRleHREaXIubWtkaXJzKCk7DQp9DQoNCkZpbGUgdGFyZ2V0RmlsZSA9IG5l
dyBGaWxlKGNvbnRleHREaXIsIGZpbGVuYW1lKTsNCmlmKCB0YXJnZXRGaWxlLmV4aXN0cygpICYm
IGFwcGVuZC5lcXVhbHMoImZhbHNlIikgKSB7DQoJdGFyZ2V0RmlsZS5kZWxldGUoKTsNCn0NCi8v
CQlCdWZmZXJlZFdyaXRlciBidyA9IG51bGw7DQpPdXRwdXRTdHJlYW1Xcml0ZXIgb3N3ID0gbnVs
bDsNCnRyeSB7DQoJYm9vbGVhbiBhcHBlbmRCb29sID0gYXBwZW5kLmVxdWFscygidHJ1ZSIpID8g
dHJ1ZSA6IGZhbHNlOw0KCWJvb2xlYW4gYWRkTmV3TGluZUJvb2wgPSBhZGROZXdMaW5lLmVxdWFs
cygidHJ1ZSIpID8gdHJ1ZSA6IGZhbHNlOw0KLy8JCQlGaWxlV3JpdGVyIGZ3ID0gbmV3IEZpbGVX
cml0ZXIodGFyZ2V0RmlsZSwgYXBwZW5kQm9vbCk7DQovLwkJCWJ3ID0gbmV3IEJ1ZmZlcmVkV3Jp
dGVyKGZ3KTsNCi8vCQkJYncud3JpdGUoc3RyaW5nKTsJCQkNCglGaWxlT3V0cHV0U3RyZWFtIGZv
cyA9IG5ldyBGaWxlT3V0cHV0U3RyZWFtKHRhcmdldEZpbGUsIGFwcGVuZEJvb2wpOw0KCWlmKCBl
bmNvZGluZyA9PSBudWxsIHx8ICIiLmVxdWFscyhlbmNvZGluZykgKSB7DQoJCW9zdyA9IG5ldyBP
dXRwdXRTdHJlYW1Xcml0ZXIoZm9zKTsJDQoJfSBlbHNlIHsNCgkJb3N3ID0gbmV3IE91dHB1dFN0
cmVhbVdyaXRlcihmb3MsIENoYXJzZXQuZm9yTmFtZShlbmNvZGluZykubmV3RW5jb2RlcigpKTsN
Cgl9DQoJaWYoIGFkZE5ld0xpbmVCb29sICkgew0KCQlzdHJpbmcgPSBzdHJpbmcgKyBTeXN0ZW0u
Z2V0UHJvcGVydHkoImxpbmUuc2VwYXJhdG9yIik7DQoJfQ0KCW9zdy53cml0ZShzdHJpbmcpOw0K
fSBjYXRjaCAoSU9FeGNlcHRpb24gZSkgew0KICAgIHRocm93IG5ldyBTZXJ2aWNlRXhjZXB0aW9u
KCJFeGNlcHRpb24gb2NjdXJlZCB3aGVuIHdyaXRpbmcgdG8gZmlsZSAiICsgdGFyZ2V0RmlsZSAr
ICI6ICIgKyBlKTsNCn0gZmluYWxseSB7DQoJdHJ5IHsNCgkJb3N3LmNsb3NlKCk7DQoJfSBjYXRj
aCAoSU9FeGNlcHRpb24gZSkgew0KCQkvLyBpZ25vcmUNCgl9DQp9DQoNCgkNCg==</value>
</Values>
