<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">getQueuedElementsChannel</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:0:required RNAME</value>
    <value>[i] field:0:required channelName</value>
    <value>[o] field:0:required outstandingEvents</value>
    <value>[o] record:1:required sharedDurableOutstandingEvents</value>
    <value>[o] - field:0:required outstandingEvents</value>
    <value>[o] - field:0:required namedObject</value>
    <value>[o] field:0:required outstandingEventsSharedDurableMax</value>
  </array>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">dHJ5IHsKCQoJLy8gcGlwZWxpbmUKCUlEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yID0gcGlwZWxp
bmUuZ2V0Q3Vyc29yKCk7CglTdHJpbmcJUk5BTUUgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKCBwaXBl
bGluZUN1cnNvciwgIlJOQU1FIiApOwoJU3RyaW5nCWNoYW5uZWxOYW1lID0gSURhdGFVdGlsLmdl
dFN0cmluZyggcGlwZWxpbmVDdXJzb3IsICJjaGFubmVsTmFtZSIgKTsKCQoJaWYoIFJOQU1FID09
IG51bGwgfHwgIiIuZXF1YWxzKFJOQU1FKSApICB7CgkJdGhyb3cgbmV3IFNlcnZpY2VFeGNlcHRp
b24oIlJOQU1FIG11c3Qgbm90IGJlIGVtcHR5LiBQcm92aWRlIGxpa2U6ICduc3A6Ly9ob3N0OnBv
cnQnLiIpOwoJfQoJaWYoIGNoYW5uZWxOYW1lID09IG51bGwgfHwgIiIuZXF1YWxzKGNoYW5uZWxO
YW1lKSApIHsKCQl0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbigiY2hhbm5lbE5hbWUgbXVzdCBu
b3QgYmUgbnVsbC4iKTsKCX0KCQoJblNlc3Npb25BdHRyaWJ1dGVzIG5zYT1uZXcgblNlc3Npb25B
dHRyaWJ1dGVzKFJOQU1FKTsKCW5TZXNzaW9uICAgICAgbXlTZXNzaW9uID0gblNlc3Npb25GYWN0
b3J5LmNyZWF0ZShuc2EpOwoJbXlTZXNzaW9uLmluaXQoKTsKCQoJbkNoYW5uZWxBdHRyaWJ1dGVz
IGF0dHJpYiA9IG5ldyBuQ2hhbm5lbEF0dHJpYnV0ZXMoKTsKICAgIGF0dHJpYi5zZXROYW1lKGNo
YW5uZWxOYW1lKTsKICAgIG5DaGFubmVsIGNoYW5uZWwgPSBteVNlc3Npb24uZmluZENoYW5uZWwo
YXR0cmliKTsKICAgIC8vIGNoZWNrIGZvciBzaGFyZWQgZHVyYWJsZQoKICAgIGlmKCBjaGFubmVs
LmdldE5hbWVkT2JqZWN0cygpLmxlbmd0aCAhPSAwICkgewogICAgCS8qCiAgICAJICogQSBzdGFu
ZGFyZCB3TSBtZXNzYWdpbmcgdHJpZ2dlciBoYXMgYSBzaGFyZWQgZHVyYWJsZSBjb25uZWN0aW9u
IGFuZCBkb2VzICJjb25jdXJyZW50IiBwcm9jZXNzaW5nLgogICAgCSAqIEZvciBzdWNoIGEgdHJp
Z2dlciBoaWRkZW4gcXVldWVzIGFyZSBjcmVhdGVkLCB3aGljaCBhcmUgTmFtZWQgT2JqZWN0cyBp
biBVTS4gCiAgICAJICovCiAgICAJSURhdGFbXSBzaGFyZWREdXJhYmxlT3V0c3RhbmRpbmdFdmVu
dHMgPSBuZXcgSURhdGFbY2hhbm5lbC5nZXROYW1lZE9iamVjdHMoKS5sZW5ndGhdOwogICAgCWxv
bmcgbWF4ID0gMDsKICAgIAluTmFtZWRPYmplY3RbXSBuYW1lZE9iamVjdHMgPSBjaGFubmVsLmdl
dE5hbWVkT2JqZWN0cygpOwogICAgCWZvciggaW50IGk9MDsgaTxzaGFyZWREdXJhYmxlT3V0c3Rh
bmRpbmdFdmVudHMubGVuZ3RoOyBpKysgKSB7CiAgICAJCW5OYW1lZE9iamVjdCBubyA9IG5hbWVk
T2JqZWN0c1tpXTsKICAgIAkJc2hhcmVkRHVyYWJsZU91dHN0YW5kaW5nRXZlbnRzW2ldID0gSURh
dGFGYWN0b3J5LmNyZWF0ZSgpOwogICAgCQlJRGF0YUN1cnNvciBzaGFyZWREdXJhYmxlT3V0c3Rh
bmRpbmdFdmVudHNDID0gc2hhcmVkRHVyYWJsZU91dHN0YW5kaW5nRXZlbnRzW2ldLmdldEN1cnNv
cigpOwogICAgCQlsb25nIG91dHN0YW5kaW5nRXZlbnRzID0gbm8uZ2V0U2hhcmVkTmFtZWRPYmpl
Y3RPdXRzdGFuZGluZ0V2ZW50cygpOwogICAgCQlJRGF0YVV0aWwucHV0KHNoYXJlZER1cmFibGVP
dXRzdGFuZGluZ0V2ZW50c0MsICJvdXRzdGFuZGluZ0V2ZW50cyIsIG91dHN0YW5kaW5nRXZlbnRz
ICsgIiIpOwogICAgCQlJRGF0YVV0aWwucHV0KHNoYXJlZER1cmFibGVPdXRzdGFuZGluZ0V2ZW50
c0MsICJuYW1lZE9iamVjdCIsIG5vLmdldE5hbWUoKSk7CiAgICAJCXNoYXJlZER1cmFibGVPdXRz
dGFuZGluZ0V2ZW50c0MuZGVzdHJveSgpOwogICAgCQlpZiggbWF4IDwgb3V0c3RhbmRpbmdFdmVu
dHMgKSB7CiAgICAJCQltYXggPSBvdXRzdGFuZGluZ0V2ZW50czsKICAgIAkJfQogICAgCX0KICAg
IAlJRGF0YVV0aWwucHV0KHBpcGVsaW5lQ3Vyc29yLCAib3V0c3RhbmRpbmdFdmVudHNTaGFyZWRE
dXJhYmxlTWF4IiwgbWF4ICsgIiIpOwogICAgCUlEYXRhVXRpbC5wdXQocGlwZWxpbmVDdXJzb3Is
ICJzaGFyZWREdXJhYmxlT3V0c3RhbmRpbmdFdmVudHMiLHNoYXJlZER1cmFibGVPdXRzdGFuZGlu
Z0V2ZW50cyk7CiAgICB9IAogICAgCgkvLyBub24gc2hhcmQgZHVyYWJsZSwKICAgIC8vIGFzIHdl
bGwgYXMgSVMgTmF0aXZlIE1lc3NhZ2luZyBUcmlnZ2VyIHdpdGggU2VyaWFsIFByb2Nlc3Npbmcg
b24gU2hhcmVkIER1cmFibGUgQ29ubmVjdGlvbiAKICAgIC8qCiAgICAgKiBJZiBhIHdNIG1lc3Nh
Z2luZyB0cmlnZ2VyIGhhcyBhIHNoYXJlZCBkdXJhYmxlIGNvbm5lY3Rpb24sIGJ1dCBkb2VzIHNl
cmlhbCBwcm9jZXNzaW5nLAogICAgICogdGhlbiB0aGUgZXZlbnQgaXMgc3RvcmVkIGRpcmVjdGx5
IGluIHRoZSBjaGFubmVsLCB0aGVyZWZvcmUgd2UgY2FuIGp1c3QgZ2V0IHRoZSBldmVudCBjb3Vu
dAogICAgICogZm9yIHRoZSB0b3BpYyAKICAgICAqLwoJSURhdGFVdGlsLnB1dChwaXBlbGluZUN1
cnNvciwgIm91dHN0YW5kaW5nRXZlbnRzIiwgY2hhbm5lbC5nZXRFdmVudENvdW50KCkgKyAiIik7
CiAgICAKICAgIHBpcGVsaW5lQ3Vyc29yLmRlc3Ryb3koKTsKCQp9IGNhdGNoIChFeGNlcHRpb24g
ZSkgewoJLy8gVE9ETyBBdXRvLWdlbmVyYXRlZCBjYXRjaCBibG9jawoJZS5wcmludFN0YWNrVHJh
Y2UoKTsKCXRocm93IG5ldyBTZXJ2aWNlRXhjZXB0aW9uKGUpOwp9CgoJCg==</value>
</Values>
