<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">generateUrl</value>
  <array name="sig" type="value" depth="1">
    <value>[i] recref:0:required connection wx.platformMonitoring.impl.http:connection</value>
    <value>[o] field:0:required url</value>
  </array>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUKSURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRDdXJz
b3IoKTsKCi8vIGNvbm5lY3Rpb24KSURhdGEJY29ubmVjdGlvbiA9IElEYXRhVXRpbC5nZXRJRGF0
YSggcGlwZWxpbmVDdXJzb3IsICJjb25uZWN0aW9uIiApOwppZiAoIGNvbm5lY3Rpb24gPT0gbnVs
bCkgewoJdGhyb3cgbmV3IFNlcnZpY2VFeGNlcHRpb24oIlByb3ZpZGUgYSBjb25uZWN0aW9uIHRv
IGNyZWF0ZSBhbiBVUkwgZnJvbS4iKTsKfQpJRGF0YUN1cnNvciBjb25uZWN0aW9uQ3Vyc29yID0g
Y29ubmVjdGlvbi5nZXRDdXJzb3IoKTsKU3RyaW5nCXByb3RvY29sID0gSURhdGFVdGlsLmdldFN0
cmluZyggY29ubmVjdGlvbkN1cnNvciwgInByb3RvY29sIiApOwpTdHJpbmcJaG9zdCA9IElEYXRh
VXRpbC5nZXRTdHJpbmcoIGNvbm5lY3Rpb25DdXJzb3IsICJob3N0IiApOwpTdHJpbmcJcG9ydCA9
IElEYXRhVXRpbC5nZXRTdHJpbmcoIGNvbm5lY3Rpb25DdXJzb3IsICJwb3J0IiApOwpTdHJpbmcJ
cGF0aCA9IElEYXRhVXRpbC5nZXRTdHJpbmcoIGNvbm5lY3Rpb25DdXJzb3IsICJwYXRoIiApOwpj
b25uZWN0aW9uQ3Vyc29yLmRlc3Ryb3koKTsKcGlwZWxpbmVDdXJzb3IuZGVzdHJveSgpOwoKaWYo
IHByb3RvY29sID09IG51bGwgfHwgIiIuZXF1YWxzKHByb3RvY29sKSApIHsKCXRocm93IG5ldyBT
ZXJ2aWNlRXhjZXB0aW9uKCJQcm92aWRlIGEgcHJvdG9jb2wgKGUuZy4gaHR0cCkiKTsKfQoKaWYo
IGhvc3QgPT0gbnVsbCB8fCAiIi5lcXVhbHMoaG9zdCkgKSB7Cgl0aHJvdyBuZXcgU2VydmljZUV4
Y2VwdGlvbigiUHJvdmlkZSBhIGhvc3QiKTsKfQoKaWYoIGhvc3QuZW5kc1dpdGgoIi8iKSApIHsK
CWhvc3QgPSBob3N0LnN1YnN0cmluZygwLCBob3N0Lmxlbmd0aCgpLTEpOwp9CgpTdHJpbmcgdXJs
ID0gcHJvdG9jb2wgKyAiOi8vIiArIGhvc3Q7CmlmKCBwb3J0ICE9IG51bGwgKSB7Cgl1cmwgKz0g
IjoiICsgcG9ydDsKfQppZiggcGF0aCAhPSBudWxsICkgewoJaWYoIHBhdGguc3RhcnRzV2l0aCgi
LyIpICkgewoJCXBhdGggPSBwYXRoLnN1YnN0cmluZygxLCBwYXRoLmxlbmd0aCgpKTsKCX0KCXVy
bCArPSAiLyIgKyBwYXRoOwp9CgovLyBwaXBlbGluZQpJRGF0YUN1cnNvciBwaXBlbGluZUN1cnNv
cl8xID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7CklEYXRhVXRpbC5wdXQoIHBpcGVsaW5lQ3Vyc29y
XzEsICJ1cmwiLCB1cmwgKTsKcGlwZWxpbmVDdXJzb3JfMS5kZXN0cm95KCk7CgoJCg==</value>
</Values>
