<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">setExtendedSettings</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsNClN0cmlu
ZwlrZXkgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKCBwaXBlbGluZUN1cnNvciwgImtleSIgKTsNClN0
cmluZwl2YWx1ZSA9IElEYXRhVXRpbC5nZXRTdHJpbmcoIHBpcGVsaW5lQ3Vyc29yLCAidmFsdWUi
ICk7DQpwaXBlbGluZUN1cnNvci5kZXN0cm95KCk7DQoNCmlmKCBrZXkgPT0gbnVsbCApIHsNCgl0
aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbigiQ2Fubm90IHNldCBleHRlbmRlZCBzZXR0aW5ncyBm
b3IgYSBudWxsIGtleSwgaS5lLiBwbGVhc2UgcHJvdmlkZSB0aGUgbmFtZSBvZiB0aGUgZXh0ZWRl
ZCBzZXR0aW5ncyB3aGljaCBzaG91bGQgYmUgc2V0IHRvICciICsgdmFsdWUgKyAiJy4iKTsNCn0N
Cg0KY29tLndtLnV0aWwuQ29uZmlnLnNldFByb3BlcnR5KGtleSwgdmFsdWUpOw0KDQoNCklEYXRh
Q3Vyc29yIHBpcGVsaW5lQ3Vyc29yXzEgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsNCklEYXRhVXRp
bC5wdXQoIHBpcGVsaW5lQ3Vyc29yXzEsICJzdWNjZXNzIiwgInRydWUiICk7DQpwaXBlbGluZUN1
cnNvcl8xLmRlc3Ryb3koKTsNCg0KCQ==</value>
</Values>
